### ISSUE TITLE
[Curitiba] Senior Go Developer na [Bornlogic]

### ISSUE THREAD

**Issue by alexrios** [Gommunity/vagas#1]
## Descrição da vaga

Backend developer com foco em golang.

## Local

Escritório, Paraná - Curitiba

## Benefícios

- Ticket refeição (vale-alimentação e/ou vale-refeição);
- Auxílio transporte (vale-transporte ou vale-combustível).

#### Diferenciais
- Não praticamos micro gerenciamento.
- Liberdade tecnologica.
- Multi cloud (Azure, AWS, GCP).
- Todos se envolvem nas discussões onde tem Know-How, não acreditamos na figura do super arquiteto ditando regras.
- DevOps como cultura e não como cargo.
- 2 niveis hierarquicos: Engenheiros & C-Level (FLAT)
- Você vai ter feedback sempre. positivo ou negativo (1:1)
- Não temos cerimônias mágicas de agilidade. Agilidade para nós é:
   * Entendemos onde estamos.
   * Damos um passo controlado para nossa meta.
   * Ajustamos baseado no entendimento do que aprendemos.
   * E repete :D

## Requisitos

**Obrigatórios:**
- 1+ ano de experiência com Golang.
- 5+ anos de experiência com desenvolvimento de software.
- Familiaridade com Docker.
- Testes unitários e de integração. Valorizamos MUITO o feedback rápido de uma aplicação com cobertura de testes.
- Experiência em implementação de API REST
- Conhecimento de pelo menos uma base de dados relacional e uma não relacional.
- Entendimento de mecanismos de autorização e autenticação (OAuth2, JWT, OpenID)
- Não ter apego com código.
- Dar direção ao produto. Você não vai receber a tarefa pronta no Issue Tracker. Vai nos ajudar a entender qual a melhor entrega para o ciclo de desenvolvimento.
- Opinar e ajustar o processo de desenvolvimento junto com a equipe buscando melhoria contínua.
- Opniões baseadas em evidências e sem bairrismo tecnológico.

**Desejáveis:**
- Usuário Linux
- Conhecimento em Kotlin ou alguma linguagem do ecossistema JVM.
- Familiarizado com Kubernetes como usuário.
- gRPC (protobuffers)

**Diferenciais:**
- Contribuições em projetos opensource.
- Base de dados baseado em grafos.
- Experiência em ambientes com alto volume de transações.
- Cálculo, estatística e probabilidade.

## Contratação

CLT

## Nossa empresa

Somos uma startup de tecnologia e nossa história conta com mais de uma década no Vale do Silício (EUA), trabalhando com algumas das maiores empresas do mundo e soma os últimos seis anos de trabalho com os maiores anunciantes da América Latina. Uma verdadeira revolução digital, que vem acontecendo desde 2013.

Nosso conhecimento e tecnologia entregam a velocidade de uma startup aos nossos clientes. Produzimos milhares de anúncios, melhorando contexto e personalizando mensagens para escalar os resultados em marketing digital.

Temos um novo produto: Gerentes Digitais (www.gerentesdigitais.com). Estamos muito orgulhosos, pois ganhamos, consistentemente, reconhecimento do mercado e parceiros. É a nossa visão de como será o marketing na próxima década. Local, digital e, principalmente, descentralizado.

## Como se candidatar

Por favor envie um email para alex@bornlogic.com com seu CV em anexo - enviar no assunto: DEV SR GOLANG.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

**Comment by alexrios** [comment]
Por favor inserir as labels:
- CLT
- Sênior
- Presencial

**Comment by delley** [comment]
@alexrios a vaga ainda está aberta?

**Comment by alexrios** [comment]
@delley sim! Obrigado por perguntar :+1:
