### ISSUE TITLE
Platform Engineer (Developer)

### ISSUE THREAD

**Issue by luisoliveira** [Gommunity/vagas#104]
## Sobre Nós
Na Captalys, nós acreditamos que o crédito é um bem comum, e assim, uma força para o desenvolvimento social e econômico.

Por isso, investimos nosso capital financeiro, humano e intelectual para desenvolver novas tecnologias que tornem esta visão uma realidade.

Nossa ambição é empoderar qualquer pessoa ou organização a investir em, ofertar, e ter acesso a crédito para que possa criar prosperidade para si, suas comunidades, e nosso futuro coletivo. 

Oferecemos soluções de financiamento para empresas e seus clientes, prestamos serviços de originação e gestão de carteiras de crédito para bancos, investidores, marcas, fintechs e marketplaces, visando aumentar o acesso e eficiência de todo o ecossistema de crédito privado.

Saiba mais: www.captalys.com.br

## Sobre a vaga
A posição de Platform Engineer (Developer) é uma oportunidade de especialização dentro da área de Infraestrutura com um perfil diferente do tradicional.

Como desenvolvedor(a), você terá o objetivo de criar soluções para automatizar os processos relacionados aos recursos da Infraestrutura de forma robusta e escalável, abrindo mão do conceito de scripts e adotando a cultura de criar ferramentas completas e/ou aplicações inteiras para isso.

Como desenvolvedor(a), você aplicará conceitos e metodologias, assim como boas práticas utilizadas por times de desenvolvimento na construção das ferramentas e/ou aplicações para a infraestrutura.

## Sobre o time
A ideia do time de Platform Engineering é construir e fornecer os recursos da infraestrutura como uma plataforma para os desenvolvedores, clientes, aplicações, etc., e para isso contamos com chapters especializados em algumas áreas (Workload, Monitoring, Development, Security e Data). 

## Sobre você
Você é curiosa(o) e tem vontade de aprender
Você se incomoda com trabalhos mal feitos
Você é aberta(o) a dar e receber feedbacks 
Você é criativa(o) e ousa propor mudanças

## O que você vai fazer

Entender as demandas dos squads de desenvolvimento e do próprio time de Platform para entregar ferramentas que automatizem e facilitem a execução de processos manuais
Construir e manter pipelines de CI/CD das aplicações
Arquitetar e estruturar sistemas para gerenciamento dos recursos da infraestrutura
Contribuir com conhecimentos gerais de software e programação para troubleshooting de problemas nos nossos sistemas

## Você vai precisar de

Formação (completa ou em andamento) em uma das duas áreas (Redes ou Desenvolvimento) e/ou experiência equivalente
Conhecimentos em pelo menos uma das linguagens de programação (Python ou Golang) 
Conhecimentos em containers (Docker)
Conhecimentos de CI/CD 
Conhecimentos de Git

## Será um diferencial se você
Manjar de AWS
Conhecer CQRS e Event Sourcing
Conhecer Istio e Kubernetes

## Local

Remoto ou Escritório, São Paulo - Itaim bibi

## Benefícios

- Plano de saúde
- Convenio com Gympass
- Seguro de vida
- VR de R$ 35/dia
- VA de R$ 500/mês

## Como se candidatar

[Acesse aqui](https://captalys.gupy.io/jobs/736272?jobBoardSource=gupy_public_page)

## Labels

- Remoto
- Alocado
- CLT
- Pleno
- Sênior
- Júnior

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
