### ISSUE TITLE
[Remoto] Sênior Software Engineer 

### ISSUE THREAD

**Issue by AirtonLira** [Gommunity/vagas#106]
## Descrição da vaga

- Atuar no desenvolvimento e manutenção de aplicações em GoLang.
- Traduzir os requisitos de negócios em arquitetura e design técnico.
- Garantir a qualidade e monitoramento das aplicações.
- Desenvolver o deploy e a integração continua de forma automatizada (CI/CD).
- Desenvolver e realizar manutenção de sistemas Event-driven.

## Local

Remoto ou Escritório João Pessoa - PB (Pós pandemia) 

## Benefícios

- Plano de saúde
- VR de R$45,50/dia
- Auxilio home-office de R$200,00/mês 
- PLR de ate 3 salários.
- Plano odontológico.
- Parceria com cursos online (Alura e 4Linux).
- Aulas particulares em inglês pela empresa.

#### Diferenciais

- Horário flexível. 
- Work anywhere.

## Requisitos

**Obrigatórios:**

- Mais de 2 anos de experiência com Golang.
- Compreensão dos conceitos de sistema distribuído, incluindo filas de mensagens (RabbitMQ ou Apache Kafka).
- Experiência com serviços em contêineres usando Kubernetes.
- Experiência com algumas das tecnologias: gRPC, REST, Webhook para criar aplicativos em nuvem.
- Conhecimento em CI/CD.
- Experiência em produtos Cloud (Azure, AWS, GCP).

**Desejáveis:**

- Experiência em algum projeto de arquiteturas orientadas a eventos com Apache Kafka.
- Experiência com GraphQL em Golang.
- Experiência com estruturas ELK - elasticsearch & Kibana.

**Diferenciais:**
- Projetos de APIs GraphQL com alto trafego de dados e requests. 

## Contratação

CLT a combinar 

## Nossa empresa

Na Conductor, o trabalho é mais que uma atividade. É um chamado para construir, projetar, codificar, pensar e colaborar. 

Nossa missão é simplificar e desburocratizar as trocas financeiras com tecnologia, agilidade, foco no cliente e práticas inovadoras.

Acreditamos que para continuarmos a ser uma empresa líder no mercado de soluções em meios de pagamentos, precisamos de um time de alta performance. Portanto, se você tem um perfil questionador, gosta de jogar em time, se adapta rapidamente às mudanças e busca sempre entregar o melhor: bem-vindo ao futuro dos meios de pagamentos e venha fazer parte da nossa história!

## Como se candidatar

Por favor envie um email para airton.junior@conductor.com.br com currículo anexado. 

## Tempo médio de feedbacks

Temos plano de carreira e um sistema de avaliação semestral.

## Labels

- Alocado
- CLT
- Senior
- GoLang
- Kubernetes
- Remoto
- Data Driven
- Event Driven

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
