### ISSUE TITLE
[Remoto] Software Engineer na Pollu-x Technology [Imediato]

### ISSUE THREAD

**Issue by lsrtgp** [Gommunity/vagas#107]
## Nossa empresa

Somos uma empresa jovem, com pessoas experientes. Profissionais com uma média de 17 anos na indústria de TI e Comunicação.

Formamos uma equipe onde a combinação de nossos talentos resulta em muito mais que aplicativos, jogos, sites, gamification, internet das coisas ou qualquer outra coisa que envolva bits e bytes.

## Local

Remoto

## Requisitos
Experiência com análise e desenvolvimento de sistemas;                                               
Experiência com GoLang , Gin (ou outro framework) e design patterns;         	
Experiência com controle de versão utilizando GIT;                                		
Conhecimento em padrões de design e arquitetura de código (Clean architecture, Microservices);                                							Experiência em desenvolvimento ágil de projetos (vivência em metodologias ágeis - Scrum, Kanban ou outros);                   							Conhecimentos em banco de dados relacional e não relacional;                              	
Experiência com arquitetura em micro serviços e testes de software;                      
Atuação em produtos digitais;                                                                                 	
Experiência com ambiente cloud (especialmente AWS);

**Desejáveis:**
Experiência com framework de mercado (React, Angular,Vue);

## Benefícios

Plano de saúde
•	Plano odontológico
•	Seguro de vida
•	VR/VA com valor mensal
•	Auxílio para aulas de inglês e espanhol
•	Horário Flexivel
•	PLR Anual

## Contratação

PJ ou CLT

## Como se candidatar

Por favor envie um email para getin@pollu-xtechnology.com com seu CV anexado - enviar no assunto: Vaga Frontend
## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- CLT
- PJ

#### Nível

- Pleno
- Sênior
- Especialista

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
