### ISSUE TITLE
[Remoto Brasil] Senior Backend Engineer na Rain (Golang)

### ISSUE THREAD

**Issue by jobsonms** [Gommunity/vagas#113]
## Descrição da vaga

A Rain Technologies Inc., fintech americana na área bem-estar financeiro procura engenheiros backend com experiência em Golang. Estamos evoluindo nosso primeiro produto, na área de 'Earned Wage Access' (EWA), e expandindo para outros países. 

As vagas são para os nossos vários squads já formados e alguns em formação. Estamos em operação nos EUA desde abril do ano passado, e agora estamos expandindo para Índia e Europa.

## Local

Remoto, qualquer lugar do Brasil.

#### Diferenciais

- Pagamento fixo em dólar (USD)
- Totalmente remoto
- Atuação internacional (EUA, India, Europa)

## Requisitos

**Obrigatórios:**
- Experiência com Golang
- Experiência com arquitetura de microserviços
- Inglês intermediário

**Desejáveis:**
- AWS, Lambda functions
- Python
- Experiência com DevOps, CI/CD
- Inglês avançado

**Diferenciais:**
- Trabalho em startups do setor financeiro
- Experiência internacional

## Contratação
PJ, valor fixo em USD por mês

## Como se candidatar

Por favor use a nossa vaga no LinkedIn: https://www.linkedin.com/jobs/view/2348460220/

## Labels

- PJ
- Remoto
- Internacional

**Comment by fernandomalmeida** [comment]
"No longer accepting applications" no linkedin, acho que pode fechar essa Issue

**Comment by jobsonms** [comment]
> "No longer accepting applications" no linkedin, acho que pode fechar essa Issue

Expirou automaticamente. Estamos reabrindo para continuar aceitando candidatos. Obrigado por avisar.

**Comment by delley** [comment]
@jobsonms essa vaga ainda está aberta?

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
