### ISSUE TITLE
[Remoto/Brasil] Site Reliability Engineer na Accenture

### ISSUE THREAD

**Issue by dblazaro** [Gommunity/vagas#125]
(LABELS: CLT; Pleno e Senior; Remoto)

Como profissional em SRE, você irá realizar entregas em diversos tipos de projeto de Dados, Analytics e Inteligência Artificial, colaborando com a arquitetura, construção, monitoramento e entrega de soluções distribuídas, resilientes, escaláveis e inovadoras.

O desafio é enorme, os projetos são muito legais e a equipe, com a participação de vocês, será ainda melhor! Buscamos pessoas que sejam colaborativas, proativas, inquietas e investigadoras.

A Accenture é lider no Brasil e na América Latina em todas as disciplinas de Dados, Analytics, Inteligência Artificial e Cloud, junte-se à nossa equipe. Todas as posições são Full-Time e CLT.

Qualificações e experiências necessárias para o desafio:

- Mínima de 5 anos em desenvolvimento de software
- Desenvolvimento de soluções distribuídas utilizando micro serviços e mensagerias
- Modelos ágeis utilizando Scrum e/ou Kanban
- Mecanismos de observabilidade (métricas, tracing, logging)
- Desenvolvimento nas seguintes linguagens: Python e GO
- Conteinerização utilizando Docker e Kubernetes
- Controle de versionamento Git
- Integração de soluções online
- Soluções de monitoração
- Sistema operacional Linux

Diferenciais como conhecimento para se destacar:

- Prometheus, Grafana, Jaeger, Zipkin, stack Elastic Search
- Experiência em desenvolvimento nas seguintes linguagens:Java, JavaScript (Node.js)
- Banco de dados não relacional (MongoDB, Cassandra, MySQL)
- Cache (Redis ou Memcached)
- Práticas de DevOps (CI/CD)
- Práticas de SRE
- Padrões arquiteturais voltados a resiliência de sistemas
- Desenvolvimento em Cloud
- Arquitetura de sistemas e de infraestrutura

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
