### ISSUE TITLE
[Remoto] Golang Developer na Bugfender

### ISSUE THREAD

**Issue by lucianosantana** [Gommunity/vagas#130]
## Descrição da vaga

Our team works on multiple platforms and SDKs, so any additional experience will be welcome! Nice additions could be things like knowledge of other web frameworks, iOS/Android development experience, usage of AWS/Azure/GCP platforms, design/UX basics, etc.

### Why working at Bugfender?
Log aggregation is an interesting engineering problem given the scale of the data being processed. Also we have many ideas to expand Bugfender’s capabilities, including data analytics, alerting, and more. We hope you can contribute to that.

Our team is made of 10 amazing people that you will interact with, but we’re still small. If you’re looking for a job where your contributions are meaningful, this is your place:

You will be entitled to make high-level decisions in engineering
We will count on you to decide on next steps, influence and shape the product
You will be able to contribute in other areas if you want to (eg. writing blog posts, customer support, marketing, sales)
In short… you will have power to change things and make Bugfender better.

Also we’re a 100% remote company (yes, most developers work from home due to COVID-19, but that doesn’t make a remote company!). You will work with a great degree of autonomy on your own flexible hours.

## Local

Remote

## Benefícios

- Flexible work schedule

## Requisitos

**Obrigatórios:**
- 2 - 4 years of experience

## Contratação

PJ (R$24.000,00 to R$27.000,00)

## Nossa empresa

**Made by developers, for developers.**
As developers at Mobile Jazz, we’ve built many apps across all mobile platforms. When doing so, however, we found a lack of good tools for remotely gathering app logs to get key information at the right time.

As developers, we share your pain points. That’s why we decided to build Bugfender — to provide the best remote logger on the market, with the options and features you need for a better development experience.

## Como se candidatar

Por favor envie um email para jobs-2021@bugfender.com com seu CV anexado (em inglês) - enviar no assunto: GoLang Developer [seu-nome]

## Labels

- PJ
- Pleno
- Remoto
- Sênior

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
