### ISSUE TITLE
[Remoto] GoLang Developer  na Cedro Technologies

### ISSUE THREAD

**Issue by KathleenOliveira** [Gommunity/vagas#131]
**CEDRO TECHNOLOGIES**

**O que você vai encontrar aqui:**

Somos uma empresa que constrói soluções transformadoras, feitas por pessoas para pessoas, pois essa é a nossa realização. Incentivamos a autonomia e a flexibilidade para que as mudanças sejam bem-vindas no nosso grupo e para que nossos colaboradores entendam que tudo pode ser inovado e melhorado. Acreditamos nas pessoas e por isso, tomamos decisões considerando o olhar do outro.

Nosso foco é atuar com tecnologias para o mercado financeiro. Estamos atuando 100% remotos, distribuídos em todo Brasil.

Nós buscamos acima de tudo profissionais que estejam buscando um novo desafio, por isso não fazemos distinção de crenças, religiões, orientação sexual ou origem. Além disso, todas nossas vagas são destinadas para PCD’s.

**O que esperamos de você?**

Buscamos profissionais apaixonados por tecnologia e pessoas. Que goste de atuar no mercado financeiro e queira crescer junto com a Cedro. Alguém que queira autonomia e busca inovar-se constantemente. Venha ser um cedrense.

**Estamos em busca de um (a) novo (a) Cedrense para somar nosso time de Desenvolvimento! O foco deste trabalho é:**

- Definição de arquitetura baseada em eventos;
- Desenvolvimento de APIs RESTfull HTTP e gRPC;
- Realizar a manutenção e criação de novas funcionalidades no back-end;
- Aplicar melhores práticas de desenvolvimento de software;
- Grande preocupação com testes automatizados, style guide, integração contínua;
- Desenvolver e sustentar integrações;
- Desenvolvimento de microsseviços escaláveis utilizando Docker/Kubernetes em cloud com arquitetura orientada a eventos.

**Quais requisitos buscamos?**

- Experiência com ferramentas de versionamento de código (GIT);
- Conhecimento em metodologias ágeis (Scrum/Kanban);
- Conhecimento em Golang, ".Net Core",  processamento em fila, WEB API, Swagger AP, PostgreSQL (ou similar);
- Desejável MongoDB.

**O que nós te oferecemos:**

- Salário compatível com o mercado;
- Benefícios flexíveis no valor de R$1.200,00 que pode ser aplicado dentro das categorias abaixo (sem desconto na folha de pagamento):
- Alimentação ou Refeição: restaurantes, lanchonetes e mercados etc;
- Mobilidade: transporte, Uber ou aluguel de carro.
- Cultura: livrarias e serviços de livros digitais, cinemas (Ingresso.com, Cinemark etc), streamings de vídeo e áudio (Spotify, Netflix, YouTube Premium etc.) etc; 
- Educação: Cursos técnicos, educação superior ou básica e cursos de idiomas;
- Saúde: Farmácias, serviços médicos/hospitalares e apps de incentivo à saúde física e mental;
- Assistência médica: Bradesco Nacional;
- Assistência odontológica: Uniodonto.

**Além disso temos outros benefícios:**

- Auxílio creche (para crianças até 02 anos);
- Horário flexível: você pode iniciar sua jornada de trabalho até às 10h;
- Crédito consignado e adiantamento salarial – Creditas.

**CONTRATAÇÃO:**  CLT

**Como se candidatar:** 

Por favor envie um e-mail com seu currículo anexado, para: **kathleen.oliveira@cedrotech.com**

**OU**

Se cadastre no nosso site: https://cedrotech.solides.jobs/vacancies/63273#vacancyDescription 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

## Labels

- Remoto
- CLT
- Pleno

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
