### ISSUE TITLE
[São Paulo] Software Engineer no Banco Cora 

### ISSUE THREAD

**Issue by AndreBorim** [Gommunity/vagas#14]
A Cora está nascendo e precisa de você para construir um novo banco.

**É tudo do zero!** Estamos escolhendo a melhor arquitetura e as melhores tecnologias para construir uma plataforma sustentável, escalável e consistente à longo prazo. Tudo isso para suportar as transações que irão alavancar o crescimento de pequenas e médias empresas em 5% ao ano.

Não buscamos uma stack específica mas developers **Go**, **Kotlin** e **Java** são muuuito aceitos, buscamos pessoas com propósito e dispostas a crescer exponencialmente com o Cora. Serão bem vindos conhecimentos em infraestrutura, clean code, e boas práticas de programação.

A contratação será feita em regime CLT, para atuar de forma presencial no WeWork, em São Paulo. Para mais informações, acesse a página da vaga.

Página da vaga: http://bit.ly/2HvIJvb

**Comment by carolinamedrado** [comment]
Pessoal, observação! O processo seletivo para essa vaga ainda está aberto!

**Comment by delley** [comment]
@AndreBorim @carolinamedrado a vaga ainda está aberta?

**Comment by AndreBorim** [comment]
Não está, Medra

Em ter., 7 de jan. de 2020 às 22:58, Francisco Oliveira <
notifications@github.com> escreveu:

**Comment by delley** [comment]
@AndreBorim @carolinamedrado a vaga ainda está aberta?

**Comment by AndreBorim** [comment]
Delley, a vaga não está mais aberta.
