### ISSUE TITLE
[Remoto] Desenvolvedor Golang na Olist na HumanAZ 

### ISSUE THREAD

**Issue by gabrielhws** [Gommunity/vagas#141]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/infobase-desenvolvedor-golang-senior-na-olist-122650035?origin=github&modal=open) com o pop-up personalizado de candidatura. 👋
<p>#Por que ser um #Dev na Olist:</p>
<p>Somos um time com o propósito de empoderar o comércio.</p>
<p>Somos colaborativos, curiosos, enfrentamos desafios diariamente e valorizamos a liberdade, autonomia e responsabilidade.</p>
<p>O time de desenvolvimento do olist, estimula autonomia e coragem.</p>
<p>Valorizamos novas ideias, criatividade, confiança, companheirismo e a diversidade.</p>
<p>Aprendemos juntos e não abrimos mão das boas práticas de desenvolvimento de software.</p>
<p>Procuramos pessoas que gostam de aprender coisas novas e que amam o que fazem.</p>
<p>#Sua jornada #Olist:</p>
<p>Você fará parte de uma equipe multidisciplinar, colaborando com os times de #front-end, #produto, #design e #negócio.</p>
<p>Desenvolver os nossos sistemas, planejando e desenvolvendo serviços e APIs em nossa plataforma de microsserviços orientada a eventos.</p>
<p>#O que você vai fazer todos os dias:</p>
<p>Ao fazer parte do #teamOlist, esperamos que você seja responsável principalmente por:</p>
<p></p>
<p>Planejar, desenvolver e implementar novas funcionalidades em nossa plataforma (SOA/Microserviços) ou APIs.</p>
<p>Você programará em #Go no desenvolvimento de aplicações em um ambiente que valoriza as boas práticas de programação (ex. testes automatizados, code review, etc)</p>
<p>Você compartilhará seu conhecimento com uma equipe fera de #Python e cheia de vontade aprender #Go.</p>

## HumanAZ : 
 <p>A HumanAZ é startup especializada na Atração de #Techpeople, especialmente – fintechs, healthtechs, edtechs, dentre outras techs que demandam um processo de atração estratégico para posições complexas.</p>

<p>Somos uma HRTech integrada a ecossistemas relevantes como o Distrito.Me e o Impact Hub, além de fazer parte do Ignite StartUps, o programa de aceleração da Qintess.</p><a href='https://coodesh.com/empresas/humanaz'>Veja mais no site</a>

 ## Habilidades: 
 - API 
- AWS 
- HTML 5 
- Javascript
## Local: 
 100% Remoto
## Requisitos: 
 - Programação Go em diferentes arquiteturas de software 
- Aplicação de HTML5, CSS3 e Javascript básico no desenvolvimento front-end; 
- Aplicação de testes automatizados e/ou TDD; 
- Modelagem e consumo de API’s REST; 
- Modelagem de bancos de dados relacionais (preferencialmente PostgreSQL); 
- Arquitetura Cloud #AWS (preferencialmente SNS e SQS); 
- Aplicação de #Git para versionamento de código; 
- Aplicação de métodos ágeis 
- Infraestrutura Cloud em #Heroku 
- Aplicação de #CircleCI para Continuous Integration
**Diferenciais:** 
 - Vivência e experiência em projeto no setor de e-commerce 
- Vivência e experiência com programação em Python, junto a Django ou Django REST Framework 
- Vivência e experiência com trabalho remoto 
- Vivência e experiência com inglês para comunicação escrita e falada

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [[Infobase] – Desenvolvedor #Golang Senior na Olist na HumanAZ ](https://coodesh.com/vagas/infobase-desenvolvedor-golang-senior-na-olist-122650035?origin=github&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção <b>Pedir Feedback</b> entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa <b>Recruiter</b> responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
PJ
#### Nível
Sênior
#### Categoria
Front-End

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
