### ISSUE TITLE
[Remoto] Backend Golang Develop na TC

### ISSUE THREAD

**Issue by pedroamoury** [Gommunity/vagas#143]
## Vaga Backend Golang - Valores acima da média !

Suas principais responsabilidades serão:
Planejar, desenvolver e implementar novas funcionalidades em nossa plataforma (SOA/Microsserviços) ou APIs
- Você trabalhará com Go no desenvolvimento de aplicações em um ambiente que valoriza as boas práticas de programação e com mais de 30 profissionais experientes em GO.
- Participar do refinamento técnico e do planejamento de entregas
Implementação de features e melhorias.
- Construção e evolução de APIs e Microsserviços..

*O que mais gostaríamos de ver?*
- Domínio de Golang, goroutines, to channels.. 
- Experiência com metodologia Ágil.
- Gostar de trabalhar com Qualidade de Código (TDD, BDD, Clean Code, Code Review)
- Modelagem e consumo de API's REST
- Git para versionamento de códigos

## Local

100% Remoto, São Paulo

## Benefícios

- Férias Remunerada
- Recesso final do ano
- Bonificações

#### Diferenciais

- Horário Flexível
- Momento Diversão
- Férias Remunerada
- Recesso final do ano
- Bonificações

## Requisitos

**Obrigatórios:**
- Experiencia com Golang 
- Experiência com Metodologia Ágil
- Experiência com banco não relacional

**Desejáveis:**
- redis

## Contratação

PJ a combinar

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até XX dias após cada processo.

E-mail para contato em caso de não haver resposta: contato@fuston.com.br

## Labels

- Alocado
- PJ
- Pleno
- Sênior
- Especialista
- Remoto

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
