### ISSUE TITLE
[Remoto] Backend Golang Developer na B2W

### ISSUE THREAD

**Issue by spitfire2903** [Gommunity/vagas#145]
## Descrição da vaga

Como desenvolvedor Back-end o profissional irá atuar junto a equipe da PLETSFORMA (desenvolvedores, arquitetos, cientistas de dados e analistas de negócio), com o papel de propor as melhores soluções e tecnologias, tendo o objetivo de sempre melhorar a experiência dos usuários e simplificar a interface entre softwares e usuários. Também irá participar da concepção de novas funcionalidades e da arquitetura dos softwares e se manter atualizado sobre tecnologias emergentes.

## Atividades

- Atuar no desenvolvimento, implementação e manutenção dos sistemas.
- Monitorar os sistemas e propor novas soluções escaláveis e robustas.
- Melhorar a experiência de desenvolvimento, compartilhando idéias e o uso de novas ferramentas.
- Realizar documentação das APIs desenvolvidas.
- Apoiar o QA no desenvolvimento de testes e planos de execuções para lançamentos de novas features.
- Aplicação de testes unitários.
- Arquiteturar novas soluções utilizando boas práticas e Design Patterns
- Dar suporte ao resto do time no desenvolvimento de novos serviços

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 450/mes
- Auxílio creche
- Desconto em toda plataforma Americanas, Submarino, Shoptime e Sou Barato
- Parceria Allya: Empresa de gestão de benefícions com mais de 30 mil empresas conveniadas, como academia, faculdade, escola de idioma, farmácia, etc

#### Diferenciais

- Ambiente Colaborativo
- Ações online o ano inteiro! Ginástica laboral, meetups com troca de conhecimento, treinamentos, etc
- Horário flexível

## Local

Remoto ou Escritório, São Paulo

## Requisitos

**Formação:**
- Superior em Exatas, preferencialmente Ciência da Computação, Engenharia da Computação, Sistemas de Informação ou Análise de Sistemas.

**Obrigatórios:**
- Experiência com Golang
- Experiência com banco de dados SQL e NoSQL
- Experiência com microserviços
- Experiência com frameworks de ORM
- Conhecimento de testes unitários e automatizados
- Conhecimento de Design Patterns
- Conhecimentos de Serverless
- Conhecimento em containers e clusters K8s
- CI/CD
- Noções básicas de Frontend
- Conhecimento de SQS/SNS, PubSub
- Conhecimento de caching e banco de dados in-memory (Redis, memcached)

**Desejáveis:**
- Experiencia com NodeJS
- Conhecimentos em Kafka
- Conhecimentos em Java
- Conhecimentos em PHP

## Contratação

CLT

## Nossa Empresa

QUER CONSTRUIR SUA CARREIRA NA MAIOR COMPANHIA DIGITAL DA AMÉRICA LATINA?
Somos a maior plataforma digital da América Latina e dona das marcas Americanas, Submarino, Shoptime e Sou Barato e temos como propósito conectar pessoas, serviços e produtos.

Surgimos como um e-commerce, que hoje reúne as marcas mais queridas da internet, mas esse foi só o começo. Com o tempo, mergulhamos de cabeça no marketplace e passamos a oferecer também serviços de tecnologia, logística, distribuição, atendimento ao cliente e meios de pagamentos digitais.

Não é uma tarefa fácil continuar crescendo nesse mercado competitivo e dinâmico, mas gostamos de desafios.

São eles que nos levam a pensar fora da caixa e a continuar inovando sempre. E para nos ajudar nesta tarefa estamos em busca de talentos que queiram transformar o mundo digital com a gente!

Se você é apaixonado(a) por entregar resultados, inovação, trabalhar de forma colaborativa e dinâmica, venha fazer parte da nossa história!

## Como se candidatar

Por favor se candidate através [desse link](https://b2w.gupy.io/jobs/954047)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: elias.fernando@b2wdigital.com

## Labels

- CLT
- Pleno
- Remoto
- Sênior

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
