### ISSUE TITLE
[Remoto] Golang Developer na Dextra

### ISSUE THREAD

**Issue by Julianapessoto88** [Gommunity/vagas#151]
## Dextra

Vem pra Dextra!

## Como será a sua atuação?

Você irá atuar nos mais diversos projetos da Dextra com as melhores práticas de código.
Atuar em equipes ágeis.
Aprender novas tecnologias / ferramentas / métodos.

## Para se juntar a nós, o que precisa saber

Já ser fera em GO ou alguma outra linguagem de programação Backend e ter grande interesse em atuar com GoLang!
Estar dentro das novas tecnologias.
Conhecimento em boas práticas e cultura ágil.
Boa comunicação e autonomia é fundamental para trabalhar em nosso ambiente dinâmico com times multidisciplinares.
Inglês avançado para conversação.

## Além disso, é um diferencial se:

Garantir a qualidade em tudo que faz, desenvolver testes unitários e/ou automatizados, bem como gostar da prática de code reviews;
Possuir flexibilidade para se arriscar em aprender e desenvolver em outras linguagens de programação;
Saber tecnologias relacionadas à Cloud Computing.
Conhecimento com CI/CD, conhecimento em docker e kubernetes.

## Local

Remoto ou Escritórios: Campinas/SP e Curitiba/PR.

## Benefícios

- Cesta de Benefício personalizada (VR, VA, V. Combusíivel e Odonto) +
- Plano de saúde
- Seguro de vida
- Auxílio creche
- Gympass
- PLR
- Auxílio Home

#### Diferenciais

- Horário Flexível
- Plano de Carreira
- Feedback 360°
- Mentoria 3.0
- Comitê de Mérito
- Estrutura Horizontal
- Treinamento de Soft Skills
- Guildas para compartilhar conhecimento.

## Contratação

CLT Full

## Nossa empresa - Dextra

Iniciamos os desafios em 2002, nossa cultura de valorização ao aprendizado gera um ambiente de colaboração e empatia que ultrapassa fronteiras! Hoje, estamos 100% remoto e vamos continuar anywhere! Somos mais de 1.000 experts em desenvolvimento de produtos digitais, combinamos metodologias de design, desenvolvimento ágil e novas tecnologias para transformar negócios. Somos agentes de transformação. A Dextra é TOP 5 das Melhores Empresas para se Trabalhar - Great Place to Work Nacional e de Tecnologia da Informação, 2020!

## Como se candidatar

Envie seu CV por aqui: https://apply.workable.com/dextra/j/18DD1A4B33/ 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

## Labels

- GO
- Remoto
- CLT
- Pleno
- Sênior

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
