### ISSUE TITLE
[Remoto] Desenvolvedor Backend Golang na OpenFlowLabs/Sphinx Tecnologia

### ISSUE THREAD

**Issue by Toasterson** [Gommunity/vagas#152]
## Descrição da vaga

Estamos à procura de Pessoas Desenvolvedoras Golang experientes para se juntar ao nosso time no projeto Regera. Nossa stack está arquitetada, e já adquirimos alguma experiência com ela. Agora queremos refinar nossos processos, e ter mais pessoas experientes envolvidas. Estou trabalhando, pessoalmente, há 5 anos com Golang, mas termos apenas um Senior (que também é responsável pela gerência) não é o suficiente.

## Local

Remoto

## Benefícios

- Aulas de inglês

#### Diferenciais

- Trabalho baseado no seu ritmo (Fazemos reuniões regularmente, tanto para garantir que as entregas estejam no caminho certo quanto para quaisquer orientações ou atividades divertidas. Todo o restante do tempo é planejado livremente por você mesmo);
- Clientes e colaboradores internacionais (Brasil/Suiça, no momento);
- Temos nossos próprios Designers de Processos;
- Estrutura de mentoria.

## Requisitos

**Obrigatórios:**

- Pelo menos 1 ano de experiência com Golang;
- 2 anos de experiência com PostgreSQL;
- Alguma experiência com fluxo de trabalho no Gitlab;
- Alguma experiência com Amazon Simple Storage Service (S3).

**Desejáveis:**
- Ter conhecimentos de Kubernetes;
- Ter conhecimentos de Containers/Docker;
- Ter conhecimentos das linguagens Markdown e PlantUML;
- Ter conhecimentos de AWS/Azure.

**Diferenciais:**
- Ter contribuído para projetos Open Source.

## Contratação

PJ ou CLT

## Nossa empresa

Estamos à procura de pessoas para se juntar ao time OpenFlowLabs/Sphinx Tecnologia, aqui no Brasil. OpenFlowLabs/Sphinx foi fundado por mim e meu sócio. Nós estudamos na Kaospilots, na Europa, e queremos ajudar startups e empreendedores a desenvolver um trabalho que tenha um impacto positivo. Nós colaboramos com startups de maneira impactante, e as ajudamos a ter sucesso em seus empreendimentos.

Atualmente, estamos trabalhando com as seguintes startups:

- Timetoplay
  Um curso de inglês para crianças pequenas aprenderem brincando. Nós ajudamos digitalizando a metodologia e escalando o negócio.
- Regera
  Uma plataforma digital para organização de Ações Judiciais Coletivas. Nós construímos a plataforma e o sistema de análise de dados.
- Wempact
  Uma plataforma para medir o Impacto de Empreendimentos Sociais, e dar voz aos beneficiários do impacto, possibilitando a comunicação e criando uma base de confiança para projetos, sendo eles de impacto gigantesco ou pequeno.

## Como se candidatar

Por favor envie um email para tech@sphinx.net.br com seu CV anexado - enviar no assunto: Vaga Remoto Backend Golang Pleno.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: tech@sphinx.net.br

## Labels

- Alocado
- CLT
- PJ
- Pleno
- Remoto
- Sênior

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
