### ISSUE TITLE
[Remoto] Backend Go Developer na GoBacklog

### ISSUE THREAD

**Issue by brenocosme** [Gommunity/vagas#153]
## Descrição da vaga

Estamos buscando uma pessoa curiosa e estudiosa, que tenha experiência no desenvolvimento produtos e soluções digitais utilizando Go como tecnologia principal, e que goste de trabalhar em ambientes jovens, dinâmicos e colaborativos. 

## Local

100% Remoto, mesmo com o fim/amenização da pandemia

## Benefícios

- Férias remuneradas
- Day off no aniversário
- Horário flexível

## Requisitos

**Obrigatórios:**
- 3 anos de experiência  trabalhando com projetos em produção utilizando GoLang como tecnologia
- Disponibilidade de responder dúvidas pontuais da equipe em horário comercial (manter a comunicação em um ambiente 100% remoto é importante)
- Conhecimento em Serverless
- Experiência com uso de bancos de dados NoSQL/SQL
- Experiência no uso de Docker e Docker Compose
- Conhecimentos CI/CD (actions, ou pipelines)
- Experiência com Git/GitHub

**Desejáveis:**
- Já ter trabalhado com softwares em produção utilizando JavaScript
- Conhecimentos em HTML5 e CSS3
- Experiência Node.js, inclusive na construção de APIs

**Diferenciais:**
- Inglês fluente 

## Contratação

PJ de R$ 7500,00 a R$ 8000,00

## Nossa empresa

A GoBacklog é uma empresa jovem, ágil, dinâmica e divertida, que idealiza e desenvolve produtos e soluções digitais para todos os segmentos do mercado (finance & trading, health & care, e-sports, energy, loyalty, music, education, etc...). Somos movidos por inovação e geralmente contratados para transformar negócios através da tecnologia.

Nosso processo de design e desenvolvimento é muito focado no negócio e na geração de valor para o cliente, e não no sistema ou aplicação em si, pois enxergamos a tecnologia como meio, e não fim. A jornada se inicia na etapa de Product Discovery, com uma profunda pesquisa do cliente, do seu mercado e das personas, passando então pela etapa de Prototype, para só então escrevermos os códigos (Product).

Assim, conseguimos criar produtos e soluções inovadoras e sustentáveis, com a melhor qualidade e usabilidade possíveis, e que realmente transformem negócios, mercados e, principalmente, a vida das pessoas para melhor. Se você também gosta de construir coisas legais e inovadoras, vem com a gente transformar o mundo! ;)

## Como se candidatar

Você pode se inscrever **[neste link](https://coodesh.com/vagas/desenvolvedor-a-backend-golang-senior-i-remoto-202053328)**, ou enviar um e-mail para o Breno (breno@gobacklog.com)

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.
E-mail para contato em caso de não haver resposta: breno@gobacklog.com

## Labels

- Go
- PJ
- Remoto
- Sênior

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
