### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora de Software BackEnd na Isaac

### ISSUE THREAD

**Issue by biarogerio** [Gommunity/vagas#156]
## Nossa empresa

A Intera está em busca de uma Pessoa Desenvolvedora de Software BackEnd para o Isaac

## Como se candidatar

Link: **https://bit.ly/3gQ5OKI**

## Descrição da vaga

- Desenvolver funcionalidade e acompanhar sua entrega até o uso do cliente final
- Dados os objetivos e problemas que o Squad precisa resolver, ajudar Product Manager a identificar as soluções de melhor custo benefício 
- Trabalhar com responsabilidade, autonomia e de forma colaborativa em Squads utilizando a metodologia ágil
- Ajudar o time com boas práticas de como Clean Code, Arquitetura orientada a microsserviços, TDD e REST APIs, além de criar soluções seguras, escaláveis e de fácil manutenibilidade
- Code-reviews, pair-programming e data-driven development farão parte do seu dia-a-dia

## Local

Remoto

## Benefícios

- Caju Benefícios: saldo mensal para uso em refeição, alimentação, mobilidade, cultura, saúde e educação
- Ambiente de crescimento acelerado, permeado de trocas e aprendizados
- Pacote de remuneração competitivo com o mercado
- Plano de saúde Amil

## Requisitos

- Bancos relacionais;
- Microsserviços;
- TDD;
- Linguagem de programação (preferencialmente Go).

## Contratação

CLT

## Labels

- CLT
- Remoto
- Sênior

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
