### ISSUE TITLE
[São Paulo/Remoto] Desenvolvedor(a) Golang Pleno na Stone

### ISSUE THREAD

**Issue by MarinaCamerano** [Gommunity/vagas#158]
## Descrição da vaga
SOBRE A VAGA:

#Desafio:

Estamos buscando Software Developers que tenham interesse em trabalhar com Go e queiram encarar conosco o desafio de fazer parte do time de tecnologia responsável pela construção da plataforma centralizada dos serviços financeiros da Stone.

Procuramos pessoas criativas, responsáveis, com energia e que tenham foco em resolver o problema do/a cliente com qualidade. Também valorizamos suas habilidades práticas de desenvolvimento e capacidade de trabalhar bem em equipe;
Você irá compor um time de desenvolvimento com o foco em: projetar, desenvolver, testar, implantar, manter e melhorar o software;
Auxiliar na construção de soluções com visão de longo prazo e qualidade;
Você irá ser um defensor das boas práticas de desenvolvimento, padrões de projeto, nossos acordos, testes, documentações e revisão de código, dentro do seu time e influenciar esta cultura o máximo possível;
Você irá aprimorar e aplicar as soluções novas e existentes as conformidades com aspectos não funcionais, tais como: performance, resiliência, segurança mantendo o foco do time em relação a estes aspectos;
É esperado de você extrema facilidade de trabalho em equipe, muita franqueza e transparência para que no dia-a-dia ter ótimo relacionamento com o time e transmitir conhecimento.

## Local

Remoto 

## Benefícios

 #Benefícios:

👩‍👩‍👦‍👦 Para aproveitar com a família: 

Convênio SESC (gratuito); 
Plano de saúde e odontológico (Bradesco TNQ2 sem co-participação);
Auxílio-creche para crianças até 5 anos.
🧘 Para melhorar o dia a dia: 

Vale Refeição e/ou Vale Alimentação.
Gympass; 
Horário flexível; 
Seguro de vida; 
Aux. Remoto para setup de trabalho e ajuda de custo mensal (a depender da posição);
Trabalho remoto (a depender da posição);
Vale Transporte (a depender da posição);
🎯 Para se desenvolver profissionalmente:

Super incentivamos idas a eventos e treinamentos, e se fizer sentido na estratégia, melhor ainda! E qualquer pessoa pode pedir; 
Trabalhar com referências técnicas; 
Eventos internos (Hackathon, Black Friday, confraternizações das Tribos e datas comemorativas);
Aprendizado contínuo, já que você vai fazer parte de uma empresa especializada em esticar pessoas.
🌎 Para influenciar a sociedade: 

Ver o seu trabalho causar impacto positivo no dia a dia de milhares de pessoas empreendedoras do Brasil na gestão de seus negócios.

# Requisitos:
O que não pode faltar

Ter escrito código em Go ou vontade de aprender;
Conhecimento de arquitetura de software;
Capacidade de produzir código limpo e de fácil manutenção;
Nível médio de leitura e escrita em inglês;
Familiaridade com Git;
Motivação por aprendizado e desenvolvimento contínuos;
Capacidade de se comunicar de forma concisa, franca e clara (também por escrito). 
O que aumentam suas chances

Ter escrito código em uma das seguintes linguagens: Python, Ruby, Elixir, Node.JS, Java ou C/C++;
Tenha conhecimento de APIs REST;
Contribuições em projetos open source;
Experiência de trabalho com times geograficamente distribuídos;
Conhecimentos de Cloud Pública (AWS, GoogleCloud, Azure...);
Experiência resolvendo problemas e otimizando a performance de APIs;
Experiência em projetos voltados para a área financeira;
Experiência com aplicações críticas e de alta disponibilidade;
Experiência com Docker e Kubernetes em produção;
Experiência com metodologias ágeis (Scrum e Kanban);
Participação em comunidades de tecnologia com palestras e afins;

## Contratação

CLT

## Nossa empresa

PRAZER, EU SOU A STECH!

Sou a área de Tecnologia da Stone, uma empresa fundada em 2012 (posso parecer neném, mas tenho muita história!). Estou crescendo bastante todos os anos, tanto no tamanho de minhas equipes como na base dos meus clientes. Hoje tenho o impacto e relevância de uma empresa grande. Mas fica de boa, ninguém perdeu a mentalidade, simplicidade, agilidade e ritmo que nos trouxeram até aqui. Quero estar ao lado da pessoa que ainda tem um comércio pequeno, que precisa lutar diariamente com o injusto. Para isso, contamos com um time fora da curva e distribuído por diversas cidades do Brasil (sim, somos um time remote-first!). Além disso, não temos medo de inovar na tecnologia para entregar os melhores produtos! Nossa stack é baseada principalmente em Elixir e Go no backend (gostamos de python também), React no frontend, serviços na AWS e apps nativos com Swift (iOS) e Kotlin (Android).

## Como se candidatar

https://boards.greenhouse.io/stone/jobs/4678372003

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
