### ISSUE TITLE
[Remoto/Recife/São Paulo] Desenvolvedor Backend Golang Sênior na Tempest

### ISSUE THREAD

**Issue by andremelo87** [Gommunity/vagas#163]
## O que fazemos no time de Engenharia de Software do AllowMe?

Nós auxiliamos empresas a prevenir fraudes e mitigar riscos de toda a jornada digital de seus clientes, construindo soluções web escaláveis e SDKs. 

## Quais os valores que temos no time?

No time buscamos cuidar das pessoas, garantir o desenvolvimento e excelência técnica. Valorizamos as pessoas, o time, o trabalho em equipe e o compartilhamento de conhecimento e ideias onde tod@s têm voz ativa, independente do cargo ou experiência.

## Sempre procuramos utilizar as boas práticas de engenharia de software, UX design e segurança, como:
Integração contínua;
Testes automatizados;
Revisão de código;
Ciclo de desenvolvimento ágil;
Monitoramento das aplicações;
Testes de segurança;
Treinamentos de segurança.

## Seus desafios serão:

Desenvolver algoritmos de alto nível que entreguem soluções para problemas reais;
Construir código testável, de alta qualidade e ótimo desempenho, consumindo apenas os recursos computacionais necessários (memória, CPU, disco e banda);
Entregar soluções end-to-end para os clientes finais, pensando, projetando, implementando e operando interfaces inteligentes e responsivas;
Ser referência técnica para os colaboradores mais juniors;
Comunicar os resultados das implementações realizadas aos times apropriados.

## O que buscamos?

Procuramos pessoas que buscam ser protagonistas de sua carreira e que queiram construir junto novos processos e contribuir para soluções inspiradoras;
Conseguir comunicar de forma clara os resultados das análises realizadas;
Experiência com linguagens de back-end, preferencialmente Go ou Java;
Experiência em ferramentas de armazenamento de dados (Postgres, S3, etc) e execução de queries usando SQL;
Experiência com o protocolo HTTP e APIs REST;
Experiência com frameworks de front-end, preferencialmente React;
Conhecimento de padrões de projetos; Conhecimento em programação orientado a eventos e mensagens;
Pensar estrategicamente. Ser capaz de visualizar o todo e entender os impactos que uma iniciativa pode gerar a partir de diversas perspectivas;
Conhecimento de arquiteturas de micro-serviços;
Conhecimento de pelo menos um mecanismo de autenticação para micro-serviços;
Conhecimento de NoSQL, em especial Redis, Memcached e/ou Cassandra;
Vivência em times ágeis (Scrum, Kanban, etc);

## Alguns diferenciais para a função:

Experiência na indústria de Cybersecurity e Anti-fraudes;
Conhecimento de boas práticas de qualidade de software como TDD e BDD;
Experiência com construção de plataformas que possuam Aplicativo Móvel (Mobile Backends);
Conhecimento de gRPC e Protobuf;
Experiência com pelo menos uma tecnologia de containerização (Docker);
Experiência com Kubernetes e outras orquestradores;

## Benefícios

- Auxílio saúde (50% custeado pela empresa);
- Auxílio odontológico;
- Vale transporte;
- Vale refeição ou alimentação;
- Tem filhos? Terá direito a um auxílio para ajudar nas despesas com escola, creche ou babá;

Na Tempest você recebe pontos para um programa de benefícios flexíveis (IPE), no qual você mesmo escolhe de acordo com o seu perfil a melhor combinação de benefícios. Ou seja, um valor flexível que pode ser alocado em: saúde, mais alimentação, capacitação, educação, academia e etc;

- Programa de Intercâmbio;
- PLR (Participação nos Lucros e Resultados): até 01 salário/ano de acordo com a política de apuração;
- MFT (Meta sob Faturamento Trimestral): até 01 salário/ano, de acordo com a política de apuração.

## Como se candidatar

https://jobs.kenoby.com/tempest/job/engenheiro-de-software-senior/61366cd8800d7425ce18b908

## Labels

- CLT
- Sênior
- Recife
- São Paulo
- Remoto

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
