### ISSUE TITLE
[Remoto/Zurich/Barcelona] Dev Go para Criptografia e Merkle Tree

### ISSUE THREAD

**Issue by jeffprestes** [Gommunity/vagas#165]
## Descrição da vaga

We are looking for talented cryptographers with strong Golang and Math background to join our core team. Your task scope will include design and implementation of the latest zero-knowledge proof systems, cryptographic protocols and Merkle Trees.

Strong background in math / cryptography / information security

## Local

Remoto ou Escritório Zurique / Barcelona - Importante: empresa não oferece suporte a conseguir visto de trabalho. Se você não tem permissão de trabalho na UE ou na Suíça você trabalhará remoto.

#### Diferenciais

Salário em Euros - Faixa de 60-80k/EUR ano, o que da por volta de R$ 30 mil reais/mês

## Requisitos

**Obrigatórios:**
- Inglês fluente
- Disposição para trabalhar a partir das 7 horas horário de Brasilia pois o trabalho é remoto mas em geral o time trabalha no mesmo fuso horário para facilitar a comunidação
- 3 anos de experiência com Go
- 2 anos de experiência com desenvolvimentos de algoritmos criptográficos.
- Saber se comunicar, não ter medo de fazer vídeo chamadas e aberto a trabalhar em equipe.

**Desejáveis:**
- conhecimentos em Ethereum
- Mestrado ou Doutorado em Matemática ou qualquer área relacionado a cálculo.

**Diferenciais:**
- projetos opensource

## Contratação

PJ

## Nossa empresa

[ https://hermez.io ] Somos uma startup que desenvolve novas tecnologias para escalar o blockchain Ethereum. Empresa dinâmica e oportunidade de aprender muito. 

## Como se candidatar

Por favor envie um email para ofra@iden3.com com seu CV em inglês anexado - enviar no assunto: Golang Dev Crypto

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 10 dias após cada processo.
E-mail para contato em caso de não haver resposta: ofra@iden3.com

## Labels

- PJ
- Remoto
- Sênior

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
