### ISSUE TITLE
[Remoto] Dev Golang e MongoDb na FinanZero

### ISSUE THREAD

**Issue by Viropelato** [Gommunity/vagas#168]
## Local

100% Remoto

## Benefícios

- A combinar

#### Diferenciais

- Fintech com muito potencial de crescimento
- Plano de carreira

## Requisitos

**Obrigatórios:**
- Xp com Go e MongoDb

**Desejáveis:**

**Diferenciais:**

## Contratação

CLT

## Nossa empresa

FinanZero

## Como se candidatar

Por favor, entre em contato comigo via Linkedin ou no meu WhatsApp (16) 996387520

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
