### ISSUE TITLE
[Remoto] Terraform/Go - Senior [CI&T] 

### ISSUE THREAD

**Issue by laichirolli** [Gommunity/vagas#175]
## Descrição da vaga
Você vai contribuir com a construção de produtos e soluções de gerenciamento da postura de segurança cloud.

Estes produtos proativamente avaliam informações de vulnerabilidade e ameaças e fornecem um contexto rico em informações que auxiliam na triagem e remediação de incidentes de segurança. Além disso, este time desenvolve blueprints em Terraform que contém as melhores práticas de segurança usadas por grandes empresas no mundo todo.

O trabalho de desenvolvimento pode acontecer em projetos open source ou internos do cliente.

## Local
100% Remoto

## Benefícios
-Plano de saúde
-Seguro de vida
-VR/ VA
-Auxílio creche
-Gympass
-PLR

## Requisitos
-Possuir experiência em automação de infraestrutura com Terraform (1+ ano);
-Ter sólida experiência em desenvolvimento em Go (3+ anos);
-Ter boa experiência com Google Cloud Platform (2+ anos);
-Ser capaz de se comunicar em Inglês (CEFR B2);
-Possuir alta capacidade de entender e desenvolver demandas com autonomia a partir de poucos requisitos, mostrando -resultados e progressos continuamente;
-Ter habilidade para testar, investigar, analisar, resolver e comunicar problemas;
-Propor e discutir soluções, e incorporar os feedbacks recebidos;
-Atuar como um engenheiro(a) completo: desde entender o problema até a entrega da solução, atuando também em testes (manuais e automatizados) e escrita técnica de manuais, tutoriais, guias ou documentação;
-Ser capaz de automatizar e otimizar tarefas de desenvolvimento;
-Gostar de aprender de forma rápida (e usar) tecnologias diferentes das que já conhece.

## Contratação
CLT
Horário flexível

## Nossa empresa
CI&T é uma digital specialist, parceira na transformação digital de ponta a ponta. Nativos digitais, temos um histórico de mais de 26 anos acelerando o impacto de negócios por meio de soluções digitais completas e escaláveis. Com a presença global de mais de 5.000 profissionais em estratégia, pesquisa, ciência de dados, design e engenharia, desbloqueamos o crescimento de receita, impulsionamos a experiência do cliente e aumentamos a eficiência operacional.

## Como se candidatar
Opção 01) Link: https://jobs.lever.co/ciandt/ff229a7a-b83a-441b-bc17-ddcdfef4d69d
Opção 02) E-mail: lailachirolli@ciandt.com

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
