### ISSUE TITLE
[São Paulo] Senior Software Engineer - GO na [TOTVS]

### ISSUE THREAD

**Issue by GuilhermeCrivelaro** [Gommunity/vagas#176]
## Descrição da vaga

- Atuar dentro de uma área de infra estrutura construindo e dando suporte a aplicações;
- Desenvolver artefatos que irão compor parte das soluções de Cloud;
- Desenvolver testes (Unitários, funcionais, Integração) garantindo e elevando a qualidade de suas entregas;
- Utilizar boas práticas e metodologias para manter um código limpo e legível;
- Fazer parte da equipe de desenvolvimento participando das decisões de arquitetura;
- Buscar aprender novas tecnologias e compartilhar com o time;
- Interagir no dia a dia com várias equipes ajudando na tomada de decisões técnicas e de negócios;
- Acompanhar evolução de outros profissionais de forma técnica com reuniões one on one.

## Local

Remoto/Escritório, São Paulo - Av. Braz Leme, 1000 - S

## Benefícios

- Universidade em Rede TOTVS, uma universidade Corporativa com conteúdos e certificações gratuitos para cada TOTVER;
- Programa +Saudáveis, que cuida de cada TOTVER com assessoria e ações voltadas para o bem estar em corpo, mente e finanças pessoais;
- Programa +Vantagens, a maior rede de descontos da América Latina, exclusivos para TOTVERS;
- Programa + Cuidado, programa de apoio pessoal para TOTVERS e familiares, com orientações em diversas especialidades como: psicologia, serviço social, pet consultoria...
- Einstein Conecta, benefício de orientação médica online pelos médicos do Hospital Israelita Albert Einstein, totalmente gratuito;
- Plano de saúde e odontológico;
- Vale refeição e / ou alimentação;
- Vale transporte e fretados em algumas estações do metrô;
- Licença maternidade e paternidade estendida;
- Espaço de lactário;
- Bicicletário;
- Vestiário;
- Seguro de vida;
- Auxílio creche;
- Previdência privada;
- Escritório que estimula a criatividade e produtividade com ambientes para lanches, salas de jogos, mesas de bilhar e poltronas para relaxar;
- Gympass.

## Requisitos

**Obrigatórios:**

Graduação e (ou) Pós-Graduação na área de tecnologia como Análise de sistemas, Ciência da computação ou Engenharia da computação
+6 anos com desenvolvimento de Software;
- Conhecimentos mínimos de desenvolvimento front-end;
- Conhecimento de Arquitetura de Software;
- Conhecimento básico de alguma nuvem públicas (Amazon, Azure, Google);
- Conhecimento de banco de dados relacional e não relacional;
- Conhecimento em Docker;
- Conhecimento em integração contínua;
- Conhecimento avançado em pelo menos uma linguagem de programação;
- Conhecimento em metodologia ágil;
- Gostar de aprender novas tecnologias;

**Desejáveis:**
- Conhecimento em linguagem GO e ou Node.js.

## Contratação
CLT - Valor a Combinar

## Nossa empresa

Aqui na TOTVS a ousadia e a transformação fazem parte da nossa rotina.

 Somos a maior empresa de tecnologia do Brasil e nosso poder de transformação faz com que nossos softwares estejam presentes em mais de 40 mil empresas no Brasil e no mundo.

O nosso grande segredo para estar sempre um passo à frente do mercado é a ousadia e a transformação que cada TOTVER promove todos os dias.
Ousadia para movimentar 25% do PIB brasileiro por meio de clientes que usam os nossos softwares.
Ousadia para ser a primeira empresa de tecnologia do Brasil a ser listada na Ibovespa.
Ousadia para fazer da mudança a nossa rotina, com mais de 40 aquisições ao longo de nossa história.
Nossa curiosidade nos impulsiona e, o melhor, todo mundo colabora com todo mundo, não importa quem deu a ideia: todas as pessoas estão dispostas a ajudar e se envolvem legitimamente para fazer dar certo e entregar resultados.
Tudo isso acontece em um ambiente leve e divertido, mas já deixamos claro: a intensidade e a rapidez com que as coisas acontecem aqui é acima da média.

Vem fazer parte de tudo isso!

## Como se candidatar

Link para candidatar-se: https://totvs.gupy.io/jobs/1307146
Por favor envie um Whatsapp para: (11) 9-50501534 
https://wa.me/5511950501534

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 15 dias após cada processo.
E-mail para contato em caso de não haver resposta: tp.g.crivelaro@totvspartners.com.br

## Labels

- CLT
- Pleno
- Remoto
- Híbrido
- Sênior

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
