### ISSUE TITLE
[Remote] Backend golang remote  at Iventis

### ISSUE THREAD

**Issue by cimerio** [Gommunity/vagas#179]
𝗕𝗔𝗖𝗞𝗘𝗡𝗗/𝗚𝗢𝗟𝗔𝗡𝗚 𝗘𝗡𝗚𝗜𝗡𝗘𝗘𝗥 | 𝗦𝗘𝗡𝗜𝗢𝗥 - 𝗘𝗫𝗣𝗘𝗥𝗧 | 𝗥𝗘𝗠𝗢𝗧𝗘
Our customer is a Global and Innovative Financial Startup. Come with Iventis and work with the most incredible projects that will redefine your career!

𝗔𝗣𝗣𝗟𝗬
Submit your Resume: recrutamento@iventis.com.br

𝗛𝗜𝗥𝗜𝗡𝗚
✔️ USD 4,500 to USD 5,500 /monthly

𝗞𝗡𝗢𝗪𝗟𝗘𝗗𝗚𝗘 𝗔𝗡𝗗 𝗦𝗞𝗜𝗟𝗟𝗦
✔️ Proficient knowledge of back-end programming languages, Go / Golang is a MUST.
✔️ Basic understanding of front-end technologies and platforms, especially React and React Native
✔️ Good understanding of server-side CSS preprocessors
✔️ Solid understanding of REST API design and development with experience building REST APIs
✔️ Experience with API security standards and implementation (OAuth,)
✔️ Good experience with API frameworks
✔️ Integration of multiple data sources and databases into one system
✔️ Management of hosting environment, including database administration and scaling an application to support load changes
✔️ Data migration, transformation, and scripting
✔️ Setup and administration of backups
✔️ Creating database schemas that represent and support business processes
#golang #backend #vagasti

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
