### ISSUE TITLE
[São Paulo] - Especialista Tecnologias Hibridas [Go/Elixir/Rust]

### ISSUE THREAD

**Issue by DablioG** [Gommunity/vagas#18]
## Descrição da vaga

FinTech que está em crescimento constante e realizando Transformação Digital, sendo o parceiro de tecnologia financeira de serviço completo que capacita os comerciantes da próxima geração a expandir seus mercados, oferecer experiências inigualáveis ​​de produtos e aumentar sua economia.

## Local

Remoto ou Escritório, São Paulo - Itaim Bibi

## Requisitos

**Obrigatórios:**
- Experiencia com Elixir, Rust, Go(Golang), Lambda(AWS)

**Desejáveis:**
- conhecimentos em tecnologias back-end(microsoft ou opensource)

**Diferenciais:**
- projetos opensource

## Contratação

PJ e/ou CLT

## Como se candidatar

Por favor envie um email para washingtonsouza@boldbr.com com seu CV anexado - enviar no assunto: Vaga Elixir

## Labels

- Alocado
- CLT
- PJ
- Pleno
- Remoto
- Sênior

**Comment by leopedroso45** [comment]
As labels estão corretas?

**Comment by delley** [comment]
@DablioG a vaga ainda está aberta?

**Comment by delley** [comment]
@DablioG a vaga ainda está aberta?

**Comment by delley** [comment]
@DablioG  a vaga ainda está aberta ou podemos fechá-la?

**Comment by DablioG** [comment]
@delley por favor, poderia deletar ?

**Comment by delley** [comment]
@DablioG estou fechando!
