### ISSUE TITLE
[Remoto] Senior Software Engineer na RAIN

### ISSUE THREAD

**Issue by CassioRoos** [Gommunity/vagas#181]
## We are looking for a Backend Software Engineer that must have some Golang experience. This position is remote. The candidate will be responsible for managing various areas of our backend platform, including API integrations with 3rd-party vendors and partners.

As a Senior Software Engineer with Rain, you will play a central role as we scale to 1M+ users. You will work with our US based product and engineering teams to implement quickly and contribute in all phases of the development lifecycle. Our ideal candidate is excited to tackle tough technical challenges and looking for opportunities to contribute to our strategic thinking.

### Responsibilities:

- Translate business requirements into technical solutions, recommend alternative technical and business approaches, and lead engineering efforts to meet aggressive timelines 
- Operational Excellence - monitoring & operation of production services including implementation of adequate resilience and high-availability models to support 24x7 operational availability
- Manage backend API integrations with 3rd-party vendors and partners
- Manage integration of user-facing elements developed by our front-end developers with server side logic
- Build reusable code and libraries for future use
- Optimize Rain application for maximum speed and scalability
- Design and implementation of data storage solutions

### Skills and Qualifications:
- Proficient knowledge of back-end programming languages, Go / Golang is a MUST.
- Basic understanding of front-end technologies and platforms, especially React and React Native
- Good understanding of server-side CSS preprocessors
- Solid understanding of REST API design and development with experience building REST APIs 
- Experience with API security standards and implementation (OAuth,)
- Good experience with API frameworks
- Integration of multiple data sources and databases into one system
- Management of hosting environment, including database administration and scaling an application to support load changes
- Data migration, transformation, and scripting
- Setup and administration of backups
- Creating database schemas that represent and support business processes

 
**Note: Examples of past work will be required as part of the hiring process**

A Bachelor’s degree in Computer Science or equivalent combination of technical education and work experience.

7+ years of Software Development experience

If you need more information feel free to contact me on https://www.linkedin.com/in/cassioroos/

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
