### ISSUE TITLE
[Remoto] Golang Software Engineer na Dev Pro

### ISSUE THREAD

**Issue by wendelkassio12** [Gommunity/vagas#183]
## Descrição da vaga

Estamos procurando um engenheiro de software talentoso e experiente para se juntar à nossa equipe de engenharia de produto colaborativa de alta qualidade. Esta não é uma função de nível iniciante, pois é necessária experiência em trabalhar com uma equipe profissional de ambiente de produção.

## Local

Totalmente remoto.

#### Diferenciais

- Budget: acima de 20.000 reais mensais

## Requisitos

**Obrigatórios:**
- Inglês avançado a fluente
- Experiência em escrever aplicativos e serviços de alta escala em Go, ou experiência comprovada em escrever aplicativos e serviços em alta escala em outras  e capacidade de aprender novas linguagens para proficiência rapidamente
- Experiência no uso de uma variedade de abordagens (ou seja, sourcing de eventos, gRPC, GraphQL) e capacidade demonstrada de escolher a abordagem certa para resolver o problema enfrentado
- Capacidade demonstrada de projetar soluções que se enquadram no panorama geral em toda a pilha (infraestrutura para navegador)
-Um código mental construtivo, aluno, curioso, inquisitivo e disposto a desafiar de forma produtiva o status quo
- Capacidade de operar em um ambiente ágil e ainda entregar código de alta qualidade em tempo hábil
- Paixão pela excelência em engenharia e compartilhamento das melhores práticas com os membros da equipe

## Contratação

PJ - (pagamento em Dólar Americano- USD)

## Empresa

Empresa americana e na indústria de Healthcare

## Como se candidatar

Por favor envie um email para wendel.kassio@devprotalent.io com seu CV anexado - enviar no assunto: Vaga Golang Senior

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 01 dia após cada processo.

## Labels

- PJ
- Remoto
- Sênior
- Golang
- USD
- Dólar
- Inglês

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
