### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora Golang Pleno na ChatPro

### ISSUE THREAD

**Issue by mvtabosa** [Gommunity/vagas#184]
## Descrição da vaga

A ChatPro está contratando pessoa desenvolvera GoLang:
Como será o seu dia a dia:

·     Desenvolver backend em Golang :slight_smile:
·     Se auto gerenciar remotamente;
·     Participar de daily meetings para alinhamento do time;
·     Participar do processo de criação dos nossos produtos;
·     Realizar commits no GitHub abrindo PRs;
·     Programar em XP com outros desenvolvedores.

## Local

Full Remoto

## Benefícios

·     100% Remoto;
·     Regime de contratação PJ;
·     Gestão Horizontal;
·     Management 3.0;
·     Metodologia ágil totalmente homologada;

#### Diferenciais

É desejável :

·     Ter experiência com Metodologia Ágil com Scrum;
·     Saber desenvolver pipelines de CI e CD;
·     Saber desenvolver testes unitários, de integração e funcionais;
·     Conhecimento para implatação na nuvem (GCP, AWS ou similar);

## Requisitos

É necessário:

·     Ter visão de tecnologia, inovação e disrupção;
·     Ter um perfil autodidata;
·     Ser responsável com as entregas e qualidade;
·     Proatividade e dinamismo;
·     Códigos sustentáveis, bem escritos e conceitos de CleanCode;
·     Saber trabalhar em equipe e o entendimento que todos somos um time;
·     Ter, no mínimo, 1 ano de experiência em GoLang e/ou 4 anos de experiência em com desenvolvimento em geral;
·     Gostar de aprender frameworks novos;
·     Ter experiência com programação para a(s) nuvem(ns) AWS, Scaleway e/ou GCP;
·     Conhecer sobre arquitetura de código.

## Contratação

PJ.

## Nossa empresa

A ChatPro é uma empresa que fornece soluções para o Whatsapp, com uma proposta inovadora utilizando o canal mais utilizado no mundo, somos a revolução na forma de automatizar, atender e até mesmo receber pagamentos. Venha fazer parte desse time incríveis de desenvolvedores
·     100% Remoto;
·     Regime de contratação PJ;
·     Gestão Horizontal;
·     Management 3.0;
·     Metodologia ágil totalmente homologada;

## Como se candidatar

Envie um e-mail para: consultoriabsafe@gmail.com com o seu CV.

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 02 dias após cada processo.
E-mail para contato em caso de não haver resposta: consultoriabsafe@gmail.com

## Labels

- Golang
- PJ
- Pleno
- Tecnologia
- Júnior
- PJ
- Pleno
- Remoto

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
