### ISSUE TITLE
[Remoto] CTO/Senior DEV na Nullwaste

### ISSUE THREAD

**Issue by mrstanleywang** [Gommunity/vagas#185]
## Descrição da vaga

Vaga para CTO de empresa recém lançada. Será o responsável pela estruturação de toda tecnologia, contratação de equipe, evolução do produto.

Backend em Go. Deverá também ter sólido conhecimento em frontend, potencialmente vue.js, Angular, React ou Flutter.

## Local

100% Remoto

## Benefícios

- Remuneração mensal de R$ 20.000,00
- VR
- VA

#### Diferenciais

- Horário flexível
- Possibilidade de trabalhar de qualquer lugar do mundo, contanto que possa estar em contato no horário comercial brasileiro

## Requisitos

**Obrigatórios:**
- 4 anos de experiência com Go

**Desejáveis:**
- conhecimento de inglês
- Experiência prévia como CTO ou gerente

**Diferenciais:**
- Possibilidade de vesting na empresa

## Contratação

PJ

## Como se candidatar

Por favor envie um email para swang@nullwaste.com com seu CV anexado - enviar no assunto: Vaga CTO

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 03 dias após cada processo.

## Labels

- PJ
- Remoto
- Sênior
- CTO

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
