### ISSUE TITLE
[Remoto] Go Software Engineer na Facily

### ISSUE THREAD

**Issue by Mariadafne** [Gommunity/vagas#186]
**Seja Python/Go Software Engineer na Facily!**

Facily é o social commerce que reúne diversos produtos a preços incríveis, para comprar com a família e amigos. Somos uma plataforma em que os usuários fazem compras em grupo para terem acesso a produtos de qualidade pelo menor preço, por meio de uma experiência de compra interativa. Estamos crescendo e nosso time também! **VEM PRA FACILY!**

**FICHA TÉCNICA**
Cargo: Python/Go Software Engineer
Departamento: Back-end
Nível: Sênior
Modelo de contratação: CLT
Local de trabalho: Remoto

Inscreva-se: https://bit.ly/3LaJfOg

## Descrição da vaga ✔

Buscamos um Senior Python Software Engineer, que atuará na construção do back-end de nossos apps, garantindo entregas de qualidade e de acordo com as regras do negócio.

Para se dar bem no nosso time, você precisa gostar de ambientes dinâmicos, ter muita proatividade e um excelente autogerenciamento. Procuramos pessoas com senso de dono e movidas por propósito, que queiram nos ajudar a construir o futuro do social commerce.

## Local

Remoto 

## Benefícios 📱💰🕐

Plano de saúde com cobertura nacional para você e dependentes 📝
Vale Alimentação ou Refeição 🥗
Horários flexíveis 🤸‍♀️
Trabalho full remote 🖥

## Requisitos

**Obrigatórios:**
- Python ou Golang (+3 anos);
- Django e FastAPI ou frameworks semelhantes;
- Programação Orientada a Objetos;
- Bancos de dados relacionais, preferencialmente MySQL e PostgreSQL.
- Algoritmos e estruturas de dados.

## Contratação

CLT

## Como se candidatar

Inscreva-se através do link: **https://bit.ly/3LaJfOg**

## Labels

- CLT
- Remoto
- Sênior

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
