### ISSUE TITLE
[Remoto] Backend Developer Go Sênior na Invillia

### ISSUE THREAD

**Issue by leandrosilva5** [Gommunity/vagas#187]
## Descrição da vaga

A Invillia é uma multinacional do ramo de produtos digitais, fornecemos soluções e produtos de alta tecnologia para nossos parceiros, como: PagSeguro, iFood, MasterCard, Gympass, Ame Digital, C6 Bank, Too Seguros, Banco Voiter, Via Varejo, entre muitos outros Players a desenvolverem seu potencial digital.

Se você busca uma oportunidade de trabalhar de onde estiver, em uma empresa dedicada em recriar a sensação de proximidade, de conexão humana, e de se sentir acolhido a qualquer momento, mesmo com todos distribuídos, aqui é o lugar certo. Faça uma imersão aqui https://invillia.com/

## Local

100% Remoto pra sempre

## Requisitos

- Go / Java
- Experiência em desenvolvimento com Spring (Boot, Data, Cache, etc);
- Experiência em microserviços e sistemas concorrentes;
- Mensageria (RabbitMQ ou Kafka)
- AWS (SNS, SQS, S3);
- Conhecimentos em Git e Git-Flow;
- Experiência com bancos de dados SQL e NoSQL;
- Desenvolvimento com foco em qualidade: testes unitários e Sonar (métricas).

## Contratação

Full CLT + Benefícios

## Como se candidatar

Por favor envie um email para leandro.oliveira@invillia.com com seu CV anexado - enviar no assunto: Vaga Go Sênior

## Informações Adicionais

A experiência de trabalhar na Invillia é única. E global. Temos o nosso próprio jeito de conectar talentos e construir inovações.
Revolucionamos o ambiente de trabalho #Instation + somos experts em desenvolver soluções complexas para #GameChangers + temos uma metodologia única #EngagedbyDataPeopleAction + investimos em pessoas #InvilliaAcademy
Alguns diferenciais Invillia:
_inovamos lado-a-lado com #GameChangersGlobais
_cultura de trabalho distribuído #inStation
_metodologia exclusiva #GlobalGrowthFramework
_benefícios únicos entre as techs #InfinitePowers

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
