### ISSUE TITLE
[Remoto] Backend Developer Go no iFood

### ISSUE THREAD

**Issue by Guilhermemaschion** [Gommunity/vagas#189]
## Descrição da vaga

Nosso objetivo é Alimentar o Futuro do Mundo, não só aplicando tecnologia de ponta, mas também por meio da Educação, Meio Ambiente e Inclusão.

Como Backend Developer Go, você irá projetar, codificar, testar serviços que impactam as principais áreas do iFood. Além disso, você também nos ajudará a construir estruturas e ferramentas para identificar gargalos de desempenho, medindo, monitorando e otimizando nosso desempenho, para garantir alta disponibilidade, escalabilidade e tolerância a falhas. Impactando diretamente a vida de milhões de pessoas diariamente!

No iFood, acreditamos na força da diversidade para gerar #Inovação e atingir #Resultados incríveis, por isso, não fazemos distinção para candidatos com deficiência, gênero, orientação sexual, raça/etnia, idade, origem, constituição familiar e estética. Temos grupos compostos por foodlovers voluntários, onde falamos sobre Raça, Gênero, LGBTQI+ e PcD, queremos ser a empresa onde pessoas escolham como lugar onde vão se desenvolver e contribuir para a realização de sonhos, #AllTogether.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Development in GO
- Strong experience of software development and their architecture;
- Good experience of automated tests, distributed systems and security concepts in development;
- Good understanding of relational and NoSQL databases;
- Experience in cloud and containerized environments;
- Be passionate about platform scalability and resilience challenges.
- At least one: Proficiency in a high-level language (Java, JavaScript, Kotlin, Swift..)

## Contratação

CLT

## Nossa empresa

Nós, FoodLovers, temos fome de inovação e resultado. Buscamos sempre fazer o nosso melhor, pensando "fora da caixa" e atuando com agilidade e responsabilidade! Temos fome de diversidade, conhecimento e compartilhamento. Trabalhamos em um ambiente de muita versatilidade. Sabe o que promove a nossa receita especial? As pessoas! Vem fazer parte disso 🤝

## Como se candidatar

Inscreva-se em nossa página de carreiras: [Backend Developer Go](https://grnh.se/1e9aee1e2us) - O link vai te levar até uma de nossas vagas de back-end que quando cadastrado será encaminhado para o time técnico onde faremos a distribuição por tecnologia. 

## Labels

- CLT
- Pleno
- Remoto
- Sênior

**Comment by braulio94** [comment]
A vaga ainda continua aberta?

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
