### ISSUE TITLE
[Portugal] Golang Developer at CAPGEMINI ENGINEERING

### ISSUE THREAD

**Issue by TaniaCapgemini** [Gommunity/vagas#204]
Hi there 🖐 
We are Capgemini Engineering. A brand part of the Capgemini Group. 
We have the mission to empower every person and every organization on the planet to achieve more. Our culture is centered on embracing a growth mindset, diversity, inclusion, a purpose of inspiring excellence, and encouraging teams and leaders to bring their best each day. In doing so, we create life-changing innovations that impact billions of lives around the world. 
You can learn more about Capgemini Engineering here: https://www.youtube.com/watch?v=MZ0Z6PjdnQo 
 
You can help us to achieve our mission! 
Now, we are part of Capgemini Group and we have more than 300,000 team members in nearly 50 countries, and we work with sectors such as aeronautics, automotive, communications, energy, life sciences, software & internet, space & defense and consumer products. 

Office , Fundão or Oporto 

#Responsibilities

- Writing scalable, robust, testable, efficient, and easily maintainable code;
- Translating software requirements into stable, working, high performance software;
- Playing a key role in architectural and design decisions, building toward an efficient micro services distributed architecture;
- Ability to train new Gophers.

#Skils

- Bachelor's degree in Computer Science or Information Technology;
- A minimum of 2 years of professional experience with Golang;
- Strong knowledge of Golang programming language, paradigms, constructs, and idioms;
- Ability to write clean and effective Godoc comments;
- Familiarity with code versioning tools;
- Good communication skills;
- Fluent in English and Portuguese mandatory, French is a plus.

#Benefits

-  Possibility to participate in international projects;
- Annual Individual Training Plan;
- Continuous training on Next1;
- Private health insurance;
- Referral bonuses for recommending your friends to Capgemini Engineering;
- Offices in great locations;
- Career evolution;

Apply Now!

You can apply for this opportunity directly by email:
tania-patricia.barata@capgemini.com

Or in Linkedin: 
https://www.linkedin.com/jobs/view/3089642913

Note: Due to the global pandemic we inform you that our recruitment process is 100% remote 🖥

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
