### ISSUE TITLE
[São Paulo] Fullstack Web Developer at SmartMEI

### ISSUE THREAD

**Issue by Leticiaschadeck** [Gommunity/vagas#21]
## Descrição da vaga 

Procuramos desenvolvedorxs Full Stack para atuar no desenvolvimento de portais WEB, com as seguintes tecnologias:
Front: ReactJS e Typescript
Backend: NodeJS, Typescrypt
Conhecimentos adicionais: GraphQL, MongoDB, Firebase e Postgres

Animado(a) em construir uma fintech de ponta para capacitar milhões de microempreendedores brasileiros? Esse é o desafio! Está a fim? Junte-se a nós :)

## Local

Escritório, São Paulo - Pinheiros

## Benefícios

- Horário flexível
- Home office
- Pertinho de duas estações de metrô
- Estacionamento de bike e ducha
- Auxílio educação

#### Diferenciais

- Snacks no escritório
- Geladeira com coca-cola

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com Node.js e React
- Conhecimento das tecnologias que usamos aqui

## Contratação

PJ a combinar

## Como se candidatar

Só clicar no link: 
https://smartmei.recruiterbox.com/jobs/fk03tvh

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: people@smartmei.com.br

## Labels

- PJ
- Pleno
- Sênior

**Comment by delley** [comment]
@Leticiaschadeck acredito que essa vaga seria mais interessantes nesses repositórios: https://github.com/frontendbr/vagas ou https://github.com/backend-br/vagas, uma vez que aqui tratamos de vagas exclusivas para Go (Golang). :+1:

**Comment by delley** [comment]
Estou fechando a issue por se tratar de uma vaga que não é relacionada com Go.
