### ISSUE TITLE
[Desenvolvedor Backend Sênior] - Remoto - CLT

### ISSUE THREAD

**Issue by luisedumoraes** [Gommunity/vagas#212]
## Empresa

A Afya Digital é um ecossistema de healthtechs. Acompanhamos os profissionais da saúde em toda a sua jornada: desde a graduação até a sua aposentadoria, pois somos movidos pelo desejo de nos tornarmos referência em educação médica e serviços tecnológicos de saúde. Para tanto, nossas soluções englobam, por exemplo: agendamento de consultas online, prescrição médica, solução para gestão financeira, telemedicina, serviços financeiros, entre outros.

A iClinc é uma das healthtechs pertencentes ao nosso ecossistema e possui a missão de descomplicar a gestão de clínicas e consultórios!!

## Descrição da vaga
Buscamos uma pessoa para o cultivo de uma cultura técnica de excelência, atuando como **Pessoa Engenheira Backend - GO**

Esperamos que você seja capaz de:

- Construir e evoluir aplicações backend com Go;
- Contribuir com a priorização e evolução do produto junto ao time, buscando a maior entrega de valor para o negócio;
- Contribuir com o desenvolvimento da equipe utilizando metodologias ágeis de desenvolvimento;
- Contribuir com pares product managers, designers e pessoas desenvolvedoras frontend na construção das aplicações;

## Local

Remoto ou Escritório, Ribeirão Preto - SP

## Benefícios

😎Para você:
- Vale Alimentação/Refeição
- Cartão de Benefício Flexível: Flash
- Gympass
- Seguro de Vida
- Plataforma de acesso a cursos
- Day-off de aniversário
- PLR
- Bônus por indicação
- Bônus por produtividade

👪Para você e sua família:
- Convênio Médico
- Convênio Odontológico
- Convênio SESC

#### Diferenciais

- Remote First
- Flexibilidade de horário
- Ambiente inovador e com segurança
- Atuar em uma empresa listada na Nasdaq

## Requisitos

**Obrigatórios:**
- Experiência na criação de aplicações backend, APIs Rest e consumo de bancos de dados SQL ou NoSQL;
- Sólido conhecimento em ao menos uma das seguintes linguagens: Go e/ou Javascript (Node);
- Experiência com testes de unidade, integração e ponta-a-ponta;
- Boas skills de comunicação, gostar de compartilhar conhecimento e ajudar colegas e pares;
- Gosta de autonomia e busca propor melhorias para projetos, times e empresa;

**Diferenciais:**
- Experiência na construção de desenhos de arquitetura de software em nuvem, utilizando AWS, GCP ou Azure;
- Experiência com armazenamento distribuído e sistemas de banco de dados (SQL ou NoSQL, ex.: PostgreSQL, MySQL, MongoDB)
- Experiência com diferentes tecnologias, não se limitando ao conhecimento atual e disposta a descobrir as melhores tecnologias para solucionar cada problema;

## Contratação

CLT

## Como se candidatar

Se inscreva no: https://iclinic-afya.gupy.io/jobs/1921016

## Labels

- CLT
- Remoto
- Sênior

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
