### ISSUE TITLE
[Remote] Senior Go Developer at  FunnelGuard

### ISSUE THREAD

**Issue by pwiszowaty** [Gommunity/vagas#22]
## Job overview

At [FunnelGuard](https://www.funnelguard.co), we help companies maximize their lead generation and customer acquisition potential. We automatically map and monitor customers' marketing funnels to provide relevant, actionable, and up-to-the-minute information so they can identify and resolve issues that stop them from acquiring customers and waste marketing budget.

You can think of us as Uptime Monitoring + Incident Response and Awareness for Marketers. We are passionate about building delightful software services to help customers succeed, and we are looking for great people to join us in that mission. You will join a small, tightly-knit team as the fourth team member to help our customers excel in their digital marketing operations. Our focus is to combine several different types of digital experience monitoring into a turn-key service built for marketers.

As a cloud engineer, you will work hand-in-hand with our team of product managers, designers, and software engineers. Together, we will develop and maintain the backend applications, services, and infrastructure that powers our monitoring stack and service UIs. We are looking for engineers who are not only passionate about building cloud systems and services but also cultivate the teams that make them. We are looking for a motivated person with the experience to solve problems at scale and versatility to embrace the challenges that arise from pushing bleeding edge technology forward.

As an early senior member of our engineering team, you will have a huge impact on our company, from the product to the team, and therefore to our customers and our growth. You will also report directly to the CTO and Co-Founder.

## Location

We're looking for remote developers located in Brazil. Our core team is located in San Francisco, CA. 

## Benefits

Our company offers exceptional compensation in the form of salary and stock options for early employees.

## Requirements

- Minimum of 8 years of professional software engineering experience on a released product or production service
- Software development experience in one or more general-purpose programming languages with an emphasis on object-oriented design and programming
- Practical working knowledge of one or more of the following: developing large scale, distributed or parallel systems, telemetry and monitoring, big data and analytics
- Experience developing in and for cloud environments; AWS, GCP, or Azure
- Good verbal and written communication skills in English
- Proficient in Golang
- Experience utilizing and developing microservices with widely used interfaces over HTTP (i.e. gRPC, REST)

## Apply
[https://apply.workable.com/funnelguard/j/E19087B511/](https://apply.workable.com/funnelguard/j/E19087B511/)

## Labels

- PJ
- Remote
- Senior

**Comment by delley** [comment]
@pwiszowaty a vaga ainda está aberta / Is the vacancy still open?

**Comment by delley** [comment]
@pwiszowaty a vaga ainda está aberta ou podemos fechá-la / Is the vacancy still open or can we close it?

**Comment by CassioRoos** [comment]
@pwiszowaty a vaga ainda esta aberta?

**Comment by delley** [comment]
Vaga aberta a mais de 6 meses. Caso a vaga ainda esteja aberta, reabra a issue.
