### ISSUE TITLE
[Remoto/Portugal] Golang Full-Stack Senior Developer

### ISSUE THREAD

**Issue by ErickaMB** [Gommunity/vagas#221]
Remota, mas precisa de realocação para Portugal (auxílio realocação), vai trabalhar no fuso de Hong Kong.

**Job Requirements:**
- 5+ years experience.
- In-depth knowledge of Apache APISIX or other API Gateways.
- Passion for open-source culture and familiarity with open-source collaboration methods.
- Good coding habits, agree with test-driven development.
- Good documentation habits.
- Familiar with service mesh and k8s ingress controller is preferred.
- Open-source project contributors are preferred.
- NGINX, Lua, OpenResty code contributors are preferred.
- **Fluent English**, Mandarin is a plus.

**Job Responsibilities:**
Develop a next-generation API management and analysis platform based on Apache APISIX.
Maintain technological innovation in API Gateway, Service Mesh, and security.
Participate in the development of Apache APISIX.

**About The Job:**
Company is recruiting NGINX/Lua/Go/API Gateway/Service Mesh Engineer for direct integration into a multinational company.

**About The Company:**
Software Consulting founded with the mission to inspire the connection of technology with people, fostering the best of our professionals through our expertise in finding and attracting the best talent for the best projects.

Se tem interesse e com requisitos da oportunidade entre em contato pelo Linkedin informando qual é a oportunidade. [[https://www.linkedin.com/in/erickamarquesb/]](https://www.linkedin.com/in/erickamarquesb/)

**Comment by delley** [comment]
Fechando vagas abertas a mais de 3 meses!
