### ISSUE TITLE
[Rio de Janeiro] Back-End Developer na B2W Digital

### ISSUE THREAD

**Issue by DioneMorais** [Gommunity/vagas#27]
==================================================
-->

## Descrição da vaga
Hey, quer trabalhar em uma companhia certificada pelo Great Place to Work?

A B2W Digital é líder na América Latina e tem como propósito CONECTAR PESSOAS, NEGÓCIOS, PRODUTOS E SERVIÇOS EM UMA PLATAFORMA DIGITAL.

A Companhia possui as maiores e mais queridas marcas da internet (Americanas.com, Submarino, Shoptime e SouBarato) e uma operação de marketplace em rápido crescimento. A plataforma construída ao longo dos últimos anos permite que a B2W Digital também ofereça serviços de tecnologia, logística, distribuição, atendimento ao cliente e pagamentos.

Somos o maior e-commerce da América Latina e buscamos Desenvolvedoras(es) Back end que queiram absorver conhecimento e se desenvolver tecnicamente com a gente, pessoas que não tenham medo de inovar, com curiosidade para experimentar novas soluções e tecnologias, com versatilidade e sede de aprendizado, com experiência na criação de soluções eficientes, escaláveis e acessíveis. Ao mesmo tempo, como prezamos por um ambiente colaborativo intra e inter equipes, gostar de compartilhar conhecimento é primordial. Acreditamos que o crescimento profissional de toda a equipe é necessário para mantermos nossa cultura focada em resultados, e, por isso, valorizamos a partilha de conhecimento a todo o instante. Então se prepare para aprender constantemente com nossas equipes!

_Nesse time, você terá a oportunidade de:_

- Desenvolver, testar, implantar, operar, monitorar e evoluir sistemas com grande volume de requisições, aplicando boas práticas de Engenharia de Software visando a qualidade, manutenibilidade, performance e segurança;
- Apoiar tecnicamente os profissionais mais juniores;
- Apoiar na concepção de arquiteturas escaláveis, práticas, metodologias, linguagens e novas funcionalidades para a plataforma.

## Local

Escritório - Saúde, Rio de Janeiro - RJ

## Benefícios

- Vale Refeição ou Alimentação;
- Assistência médica e odontológica; 
-Vale transporte; 
- Seguro de vida;
- Club de compras com descontos exclusivos nas nossas marcas;

#### Diferenciais

- Fazemos nossa proposta salarial de acordo com a sua pretensão, avaliação técnica e nosso plano de cargos e salários, para que tenha a sua cara;
- Horário flexível;
- Vans e ônibus para levar nossa galera com conforto até pontos estratégicos do Centro(RJ);
- Meetups e eventos de tecnologia para troca de conhecimento;
- Muitos eventos internos: aniversariantes do mês, aniversário das marcas, festa junina, Halloween, black friday, entre outros;
- Áreas de descompressão como: shiatsu, sinuca, biblioteca, cadeira de massagem e vídeo game;
- Copa para refeições;
- Uma filial das Lojas Americanas dentro do nosso escritório para chamar de nossa <3;
- Dress code informal: Uso de bermuda liberado \o/

## Requisitos

**Obrigatórios:**
- Ter experiência consolidada em Golang ou Java;
- Dominio em testes automatizado de Software;
- Experiencia com versionamento de código com GIT;
- Experiencia em CI / CD;
- Saber como funciona o protocolo HTTP e o padrão REST;
- Sólidos conhecimentos nas boas práticas de Engenharia de Software;
- Capacidade analítica/raciocínio lógico (problem solving/algoritmo);
- Graduação completa em Ciência da Computação ou áreas relacionadas ou experiência profissional equivalente;
- Trabalho em equipe.

**Desejáveis:**
- Ter conhecimento sobre Domain Driven Design;
- Ter conhecimento sobre melhores práticas no desenvolvimento de software (SOLID, KISS, DRY e YAGNI);
- Ter experiência com Serviços de mensageria.

**Diferenciais:**
- Experiência com Terraform;
- Experiência com Kubernetes;
- Experiência com infra-estrutura em nuvem na AWS ou equivalente;
- Experiência com arquitetura de Sistemas Distribuídos.

## Contratação

CLT

## Nossa empresa 

_Quer saber mais sobre o BIT?_

O BIT é o Hub tecnológico da B2W Digital; sua sigla significa: _B2W Inovação e Tecnologia._ Nossos times trabalham com _metodologias ágeis_. Os times têm _autonomia_ em como desenvolver os produtos e serviços, o que significa que escolhem as _tecnologias utilizadas_ e a metodologia ágil de trabalho que possibilite agilidade nas entregas.

Somos movidos a resultados e trabalhamos para entregar soluções valiosas aos nossos clientes. Encorajamos _pair-programming_ e as interações diárias, porque acreditamos que o sucesso vem da diversidade, autonomia e colaboração. Trabalhamos em um ambiente _“open space”_, com diversas áreas e espaços colaborativos. Sim! Nós também temos Hackaton, o IronBit, e é muito divertido. Nessa maratona, qualquer pessoa tem a oportunidade de implementar sua ideia.

Somos apaixonados por tecnologia e gostamos de compartilhar isso com a comunidade. Por isso, participamos dos principais eventos de tecnologia do país como patrocinadores e como palestrantes (QCon, TDC, Big Data Week, Campus Party e Velocity). Também abrimos nossos espaços para receber os Meetups das comunidades de tecnologia, e, mais recentemente, disponibilizamos para a comunidade os projetos open-source Marvin (https://marvin.incubator.apache.org/) e RestQL (http://restql.b2w.io/).

 _Diversidade e Inclusão_
Queremos entregar tudo, a toda hora e em qualquer lugar. Para isso, estamos construindo uma equipe cada vez mais diversa, composta por pessoas criativas, engajadas e que respiram inovação e tecnologia. Buscamos oferecer oportunidades iguais a todas as pessoas, independente de gênero, etnia, religião ou orientação sexual. Aqui as pessoas têm voz e são incentivadas a desenvolver projetos disruptivos. Vem transformar o mundo digital!

## Como se candidatar

Diretamente pela nossa página de carreiras: https://b2w.gupy.io/jobs/208978

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 7 dias após cada processo.

## Labels

- Go
- Java
- CLT
- Pleno

**Comment by delley** [comment]
@DioneMorais a vaga ainda está aberta ou podemos fechá-la?

**Comment by delley** [comment]
Vaga aberta a mais de 6 meses. Caso a vaga ainda esteja aberta, reabra a issue.
