### ISSUE TITLE
[São Paulo] Desenvolvedor Golang Sênior no Traders Club

### ISSUE THREAD

**Issue by TradersClub1** [Gommunity/vagas#39]
Somos a maior plataforma de investidores da América Latina e triplicamos o nosso time nesse último trimestre.
Se você é apaixonado por tecnologia e quer trabalhar em uma empresa com propósito, o TC é o lugar certo!

Estamos com oportunidades para Desenvolvedor Golang, para fazer parte do nosso time de Tech ; )

O que irá fazer?

- Levantamento de requisitos.
- Desenvolvimentos em Golang.
- Atuação com banco de dados.

Requisitos

- Experiência sênior em Golang.
- Conhecimento em banco de dados MongoDB e MyCircle.

Diferenciais
- Conhecimento em Node e React.

Contratação PJ 
Assistência Médica
Vale Refeição
Gympass
Jornada de trabalho flexível
No dress code
Ambiente com espaço para descompressão, frutas e snacks à vontade.

Para se candidatura, envie o currículo para o email: juliana.morgado@tradersclub.com.br

## Labels

- PJ
- Sênior

**Comment by delley** [comment]
@TradersClub1 essa vaga ainda está aberta ou podemos fechá-la?

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
