### ISSUE TITLE
[Rio de Janeiro] Back-End Developer na B2W Digital

### ISSUE THREAD

**Issue by fellipenascimento** [Gommunity/vagas#4]
## Descrição da vaga

A vaga destina-se a desenvolvedores Pleno e/ou Sênior na linguagem Go, que irão trabalhar em APIs REST usando nosql. 

Mais informações sobre a vaga podem ser encontrados neste endereço: https://b2w.gupy.io/jobs/59773

## Local

Escritório, Rio de Janeiro - Praça Mauá, - Centro.

## Benefícios

- Vale refeição ou Vale alimentação 
- Vale transporte
- Plano de saúde e odontológico
- Seguro de vida

#### Diferenciais

- 10% de Descontos do Funcionário: em compras com crachá nas Lojas Americanas e em nossos sites (Americanas.com, Submarino, Shoptime e SouBarato)
- Bicicletário: possuímos bicicletário e vestiários para os associados que optam por vir pedalando para o trabalho
- Shiatsu: semanalmente disponibilizamos sessões de shiatsu de 15 min
- 5a às 5h: evento semanal de troca de conhecimento apresentado na nossa Arena.  

## Requisitos

**Obrigatórios:**
- 1+ ano de experiência com Golang.
- 4+ anos de experiência com desenvolvimento de software.
- Familiaridade com Docker.
- Testes unitários e de integração. Valorizamos MUITO o feedback rápido de uma aplicação com cobertura de testes.
- Experiência em implementação de API REST
- Conhecimento de pelo menos uma base de dados não relacional.
- Opinar e ajustar o processo de desenvolvimento junto com a equipe buscando melhoria contínua.
- Opniões baseadas em evidências e sem bairrismo tecnológico.

**Desejáveis:**
- Familiarizado com Kubernetes como usuário.

## Contratação

CLT

## Nossa empresa

Temos a missão de manter e evoluir uma das plataformas mais complexas e robustas da internet. Uma enorme parcela de tudo que é vendido online no Brasil tem como vitrine os sites Americanas.com, Submarino, Shoptime e Sou Barato. Os nossos números são absurdos, veja:

180 page-views por segundo;
21 milhões de visitantes únicos por mês (ou 270 Maracanãs lotados);
1 milhão de produtos distintos sendo oferecidos nos sites;
14 buscas realizadas nos sites a cada segundo;
Terabytes de dados são gerados todos os dias.

Para isso, precisamos operar alguns dos sistemas mais robustos e complexos da internet. Por trás deles, está uma arquitetura state-of-the-art que combina os padrões e tecnologias mais modernas do mercado. São centenas de aplicações diferentes rodando em ambiente de alta-escalabilidade e que precisam responder muito rápido para não deixar nossos clientes esperando. Até mesmo no Black Friday, quando tudo que construímos é posto à prova. Nesse evento, as interações com os sites aumentam 20 vezes, em média.

## Como se candidatar

Acesse https://b2w.gupy.io/jobs/59773 e clique em Candidatar-se para a vaga.
                

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.

## Labels

- CLT
- Sênior
- Pleno
- Presencial

**Comment by delley** [comment]
@fellipenascimento a vaga ainda está aberta?

**Comment by fellipenascimento** [comment]
Oi,
ainda estamos com vagas em aberto.

https://b2w.gupy.io/jobs/59773


Em ter., 7 de jan. de 2020 às 22:53, Francisco Oliveira <
notifications@github.com> escreveu:

**Comment by delley** [comment]
@fellipenascimento a vaga ainda está aberta?

**Comment by CassioRoos** [comment]
@fellipenascimento a vaga ainda esta aberta?

**Comment by fellipenascimento** [comment]
@CassioRoos @delley ainda temos vagas!

**Comment by delley** [comment]
@fellipenascimento essa vaga ainda está aberta ou podemos fechá-la?

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
