### ISSUE TITLE
[Remoto] Software Developer (Go) na Stone

### ISSUE THREAD

**Issue by alexgarzao** [Gommunity/vagas#40]
## Descrição da vaga

Estamos buscando Software Developers que tenham interesse em trabalhar com Go e queiram encarar conosco o desafio de construir a Conta Stone, nos ajudando nas principais decisões técnicas e seus impactos no produto no médio/longo prazo.

Nossa stack atual é baseada principalmente em Elixir no backend (gostamos de python também), React e Elm no frontend, bancos de dados Postgres e ElasticSearch, e serviços na AWS e GCP.

Além da stack em Elixir, temos uma nova Stack em Go, onde temos alguns projetos e vários profissionais atuando no momento.

## Local

Remoto ou presencial na sede do Rio de Janeiro.

## Benefícios

- Plano de saúde
- Seguro de vida
- VR ou VA
- Auxílio creche

## Requisitos

**Obrigatórios:**

- Ter escrito código em Go ou vontade de aprender;
- Conhecimento de arquitetura de software;
- Capacidade de produzir código limpo e de fácil manutenção;
- Nível médio de leitura e escrita em inglês;
- Familiaridade com Git;
- Motivação por aprendizado e desenvolvimento contínuos;
- Capacidade de se comunicar de forma concisa, franca e clara (também por escrito);

**Diferenciais:**

- Ter escrito código em uma das seguintes linguagens: Python, Ruby, Elixir, Node.JS, Java ou C/C++;
- Tenha conhecimento de APIs REST;
- Contribuições em projetos open source;
- Experiência de trabalho com times geograficamente distribuídos;
- Conhecimentos de Cloud Pública (AWS, GoogleCloud, Azure...);
- Experiência resolvendo problemas e otimizando a performance de APIs;
- Experiência em projetos voltados para a área financeira;
- Experiência com aplicações críticas e de alta disponibilidade;
- Experiência com Docker e Kubernetes em produção;
- Experiência com metodologias ágeis (Scrum e Kanban);
- Participação em comunidades de tecnologia com palestras e afins;

## Seniority Level

Júnior, pleno ou sênior

## Contratação

Tempo integral, CLT ou estágio.

## Nossa empresa

https://www.stone.com.br/

## Como se candidatar

https://www.linkedin.com/jobs/view/1914591219/

**Comment by mrangel-jr** [comment]
Me candidatei pelo LinkedIn lá !

**Comment by agsvensson** [comment]
@alexgarzao, enviei para estágio!  :)

**Comment by NauanyC** [comment]
Vaga com Golang não dá pra não candidatar!

**Comment by delley** [comment]
@alexgarzao essa vaga ainda está aberta ou podemos fechá-la?

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
