### ISSUE TITLE
REMOTO - Developer Go - Infrastructure and API development - Salario em Dolar Canadense + Equity

### ISSUE THREAD

**Issue by edurmaciel** [Gommunity/vagas#43]
## Descrição da vaga

We're looking for someone with experience writing and shipping production-quality code in Go. You have a refined eye for rigorous, clean code, but are able to balance tradeoffs inherent in all design decisions.

You enjoy building scalable, fault-tolerant systems. You understand the meaning of value, too, and in the end it's about delivering products that achieve business outcomes while laying the foundation of great tech that effects our entire org, and is impactful. This matters to you.

Given the size of our client, self-driven engineers will thrive best in this role. While small, you'll be working alongside some of the best engineers, and open-source contributors--and a company dedicated to your success. You will learn a lot.

## Responsabilidades

- Architect, develop, and contribute to the infrastructure and API development
- Write open source work

## Local

100% Remoto

## Benefícios

- Salário acima da média, trabalho 100% remoto e possibilidade de imigrar para o Canada no futuro.

## Requisitos

**Obrigatórios:**
​- Fluent in spoken English. No other Portuguese speakers in the team.
- Experience shipping production-grade code in Go.
- Knowledge of distributed systems design.
- Experience with one of the major cloud providers, AWS, GCP, Azure, etc.

**Desejáveis:**
- Prior blockchain knowledge is not required, but is a bonus.

**Diferenciais:**
- projetos opensource

## Contratação

CLT ou PJ a combinar

## Como se candidatar

Processo simples: Basta fornecer o nome, email e CV neste site: https://sundae.zohorecruit.com/jobs/Careers/595478000000313084/Go-Developer?source=CareerSite

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 2 dias após cada processo.
E-mail para contato em caso de não haver resposta: hello@sundae.cat

## Labels

- CLT
- PJ
- Pleno para Sênior
- Sênior
- Remoto

**Comment by ozzono** [comment]
Acho que esse processo seletivo já foi encerrado.

**Comment by delley** [comment]
Link para vaga não existe mais. Estou fechando a issue!
