### ISSUE TITLE
[Remoto] Senior Golang Developer na E-CORE

### ISSUE THREAD

**Issue by Jhcallegaro** [Gommunity/vagas#45]
## Descrição da vaga

Buscamos uma pessoa para atuar como Senior Golang Developer e ajudar empresas a acelerar e otimizar seus recursos de entrega digital através de soluções de software.

## Local

Remoto

## Benefícios

- Seguros de saúde, odontológico e de vida;
- Vale Refeição e/ou Alimentação;
- Plano de Previdência Privada;
- Apoio financeiro para estudos e creche;
- Sem código de vestimenta: seja você mesmo, seja o seu melhor;
- Horário de trabalho flexível;
- Entre outros.

#### Diferenciais

- Projetos internacionais
- Cultura de transparência e colaboração
- Tecnologias de ponta
- Eventos e celebrações
- Ambiente de trabalho amigável
- Networking com profissionais qualificados

## Durante o seu dia cojmo Senior Golang Developer, você vai: 

- Crie arquiteturas escaláveis ​​e sustentáveis;
- Desenvolver código reutilizável, testável e eficiente;
- Buscar ativamente inovação e melhoria contínua, além de eficiência em todas as tarefas atribuídas;
- Comunicar com partes interessadas e monitar o impacto das features;
- Reforçar uma cultura de excelência em engenharia de software.

## Como Senior Golang Developer, você tem:

- Experiência sólida e relevante em desenvolvimento de software em geral;
- Experiência trabalhando com Go;
- Conhecimento para escrever códigos testáveis e de alta qualidade; 
- Experiência na aplicação de fundamentos da ciência da computação: estruturas de dados, projeto de algoritmos, resolução de problemas e análise de complexidade.

## Contratação

CLT

## Sobre a e-Core

Na e-Core, nossos times são apaixonados pelo o que fazem e acreditam na construção de um futuro melhor. Garantimos um clima de trabalho inspirador, guiado por nosso propósito e valores institucionais. Até hoje, fomos premiados como um Great Place To Work por 12 anos consecutivos e, em 2019, reconhecidos como um dos Melhores Lugares para Trabalhar pelo Glassdoor.

Adoraríamos contar com você em nosso time!

Pessoas com deficiência são bem-vindas!

## Como se candidatar

Confira todos os requisitos e cadastre o seu CV em: https://bit.ly/3iHqGSO

## Labels

- Golang
- Remoto
- Sênior
- CLT

**Comment by agsvensson** [comment]
E-Core, me chama para estágio em Go! (Vai que dá certo...) :)

**Comment by renanbastos93** [comment]
> E-Core, me chama para estágio em Go! (Vai que dá certo...) :)

olha aí o cara querendo trabalhar em, ta valendo da essa oportunidade para ele!

**Comment by delley** [comment]
@Jhcallegaro essa vaga ainda está aberta?

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
