### ISSUE TITLE
[Remoto] Go Developer na Salú

### ISSUE THREAD

**Issue by miguelpragier** [Gommunity/vagas#51]
## Backend GO Developer

Oportunidade para GOLang Developer, com ao menos 3 anos de experiência em desenvolvimento de sistemas, e no mínimo 1 ano de experiência em linguagem Go.

## Local

Remoto /  HomeOffice
Após a pandemia, reabriremos nosso escritório em São Paulo (SP), e o profissional poderá optar por trabalhar lá, caso queira.

## Responsabilidades Principais

- Desenvolvimento serverside de serviços em linguagem GO;
- Colaboração, versionamento e publicação de software em staging e produção;
- Construção de APIs;
- Integração com APIs de terceiros;
- Implementação de testes unitários e de integração;
- Documentação completa e detalhada

## Requisitos

- Pelo menos três anos de experiência profissional em desenvolvimento de software;
- Um ano de experiência profissional em linguagem GO;
- APIs REST;
- Base teórica de computação, em faculdade, curso médio ou curso livre;
- Conhecimento intermediário em SQL;
- Conhecimento intermediário em Linux;
- Inglês para leitura técnica;
- GIT :: Domínio dos comandos principais;
- Curiosidade técnica e empenho para estudo;
- Código legível e idiomático;
- Atenção com a qualidade da entrega;
- Profissionalismo;
- Tem que gostar muito de programar!

## Condições

- Contratação PJ ou CLT;
- Horário das 9h às 18h ( Com alguma flexibilidade )
- Salário de R$ 6000 (PJ)
 

## Processo Seletivo

- 100% online;
- Análise do material enviado ou referenciado no e-mail de candidatura;
- Conversa para conhecer a(o) candidata(o), e para apresentar a empresa;
- Conversa sobre engenharia de software;
- Teste rápido de codificação online;
- Conversa com os gestores e o time dev;

## Como se candidatar

- Envie um e-mail para miguel@salu.com.vc, com assunto: Vaga DEV GO;
- Inclua portfolio, repositório Github, currículo, Linkedin e todo material que demonstre seu nível técnico e  histórico profissional e acadêmico;
- Conte na mensagem o quê lhe interessou na vaga;
- Indique algum projeto/repositório feito em GO que admire, e explique o porquê.
- Certifique-se de haver lido, entendido e cumprido estes itens da candidatura. Isso nos demonstra que você é bom em ler e compreender especificações escritas. :-)
 

## Tempo médio de retorno: uma semana
E-mail para contato em caso de não haver resposta é o mesmo da candidatura.

## Nossa cultura e nossos valores

- Valorizamos muito a boa educação, a gentileza e a atitude positiva;
- Gostamos de diversidade;
- Nos entendemos bem porque nos comunicamos bem;
- Nós nos ajudamos a crescer como pessoas e profissionais;
- Vontade de aprender é essencial;
- Liberdade com responsabilidade;
- A empresa ainda é pequena, e nossos processos simples, ágeis e desburocratizados;

## Recados pra você, que se interessou pela vaga

Nosso time é composto por gente bacana, qualificada e amigável. Mas nossos robôs são desafiantes e insensíveis, e tendem a ficar bem complexos. Isso exige atitude, perseverança, curiosidade e capacidade diagnóstica.
Como time, esperamos que os membros sejam disciplinados, colaborativos, humildes e honestos.
Esta é uma posição que exige dedicação exclusiva, e disponibilidade integral durante nosso horário de trabalho.

## Nossa empresa

A Salú nasceu em 2019, com a missão de aproximar as pessoas dos cuidados com sua própria saúde.
Nosso app mobile é um assistente digital de saúde, com telemedicina por voz e vídeo, e checagem de sintomas.
Recentemente fomos capitalizados por investidores dos setores de tecnologia e medicina.
Somos orgulhosos por termos sido acelerados pelo [Banco C6](https://medium.com/c6banknoticias/conhe%C3%A7a-as-seis-startups-selecionadas-para-a-2%C2%AA-turma-do-opp-3492380a172f) entre 2019 e 2020, e atualmente pelos pesos-pesados [Eintein Eretz](https://eretz.bio/startups/salu/) e pela [Quintessa](https://www.quintessa.org.br/portfolio/areas-de-impacto/saude/#saude-logos).
Para saber mais sobre a Salú, visite [nosso website](https://salu.com.vc/)
Nossa operação comercial já iniciou e nosso backlog cresce exponencialmente. Hora de aumentar o time!

## Labels
- CLT
- PJ
- Pleno
- Remoto

**Comment by salu-miguel** [comment]
Por favor, pode encerrar esta vaga.
Já contratamos por outro canal.

Muito obrigado!

**Comment by delley** [comment]
Ok!
