### ISSUE TITLE
[São Paulo] Back-end Developer Senior Golang @gobettirh

### ISSUE THREAD

**Issue by gobettirh** [Gommunity/vagas#52]
## Descrição da vaga

O contratado participará do processo de estruturação da área, podendo trazer sua visão e experiência para agregar ainda mais valor ao time, podendo até realizar contratações para sua equipe. O aprovado será o braço direito do coordenador da área.

## Local

Inicialmente Remoto e pós-pandemia Av. Brigadeiro Faria Lima, São Paulo

## Benefícios

- VT
- Vale-Refeição
- Vale-Alimentação
- Assistência Médica

## Requisitos

**Obrigatórios:**

- Golang;
- Sólidos conhecimentos em linguagens de programação;
- Experiência com gestão de times;
- Experiência com arquitetura de projetos

**Diferenciais:**
- Kubernetes; Google Cloud; GraphQL; RabbitMQ; MongoDB.

## Contratação

CLT

## Nossa empresa

Empresa desenvolve um aplicativo de investimentos onde o cliente realiza a gestão de seus investimentos e controle financeiro. Empresa com 30 colaboradores.

## Como se candidatar

Por favor, envie um email para **sandra@gobettirh.com.br** com seu **CV anexado e pretensão salarial**. 
Informar no assunto: Vaga Golang

## Tempo médio de feedbacks

A partir do dia 21/09/2020.

## Labels

- CLT
- Inicialmente Remoto
- Sênior
- Golang

**Comment by delley** [comment]
@gobettirh essa vaga ainda está aberta ou podemos fechá-la?

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
