### ISSUE TITLE
[Remoto] Junior Full Stack Developer at DB1 Group

### ISSUE THREAD

**Issue by cristianeabe** [Gommunity/vagas#53]
## Job description

Have you ever thought about coding using Golang, Angular, Vue, and microservices in an international and multicultural team to support and evolve a software used worldwide helping more than 65k users?! Sounds good? That's the chance we are offering you! 

## Location

Remote or located in one of our offices (Maringá-PR; Campo Grande-MS; Presidente Prudente-SP)

## Requirements

**Here’s what we’re looking for:**
- Previous experience with Golang and/or Angular;
- Git;
- English conversation is a must!

**It would be great if you had these desirable Skills/Experience:**
- SQL and NoSQL databases;
- It's a plus if you have knowledge/experience with scrum, microsservices, and/or AWS

## Category of worker

CLT

## Benefits

- Healthcare plan; 
- Meal Voucher/Supermarket Voucher;
- Equipment offered by the company (computer, monitor, keyboard, mouse, headset).

#### Differentials

- Work with amazing people that love to share knowledge;
- Be in a camaraderie environment where teamwork is the most important; 
- Face challenges to reach personal and professional development;
- Work with a flexible schedule;
- Be part of different committees that take actions that impacts DB1 as well as our society. 

## Our company

We are a technology group with 19 years of expertise in software development, aimed to design solutions to big companies. We're ten years in a row among the best places to work, according to GPTW rank.
Being DB1 is to belong to a group that transforms companies and people's lives through technology. Our culture, knowledge, and skills move us to deliver results that help people in their daily life.

## How to apply

You can send your resume in this link:  https://vagasdb1.recruiterbox.com/jobs/fk0qgrm?source=Github
Or you can send it by email: vagasdb1-vgsd0309@applications.recruiterbox.com

## Labels

- Remote
- CLT
- Junior

**Comment by delley** [comment]
@cristianeabe essa vaga ainda está aberta ou podemos fechá-la?

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
