### ISSUE TITLE
[São Paulo] Fullstack Mobile Developer na SmartMEI

### ISSUE THREAD

**Issue by Leticiaschadeck** [Gommunity/vagas#67]
## Descrição da vaga

Você fará parte do time de engenharia e ficará alocado na equipe de Mobile atuando como Fullstack.
Nossa aplicação mobile é construída em Flutter, e o nosso Backend é escrito em Node, Typescript e Golang. Nossa infraestrutura é totalmente em nuvem, AWS e Google Cloud. 

## Local

Remoto ou Escritório, São Paulo - Pinheiros

## Benefícios

- Férias (11 dias úteis a cada 6 meses)
- Auxílio educação, reembolso de 50%
- Contas no Alura pra treinamento
- 40% de subsídio para psicoterapia
- Licença paternidade e maternidade
- Day off no mês do aniversário

#### Diferenciais

- Open Coca-Cola na geladeira
- Modelo remoto antes e depois da pandemia

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com backend em Node ou Typescript
- 2 anos de experiência em mobile

**Desejáveis:**
- Experiência no back com Go
- Experiência mobile com Flutter

## Contratação

PJ com benefícios

## Nossa empresa

A SmartMEI é uma startup, fintech, com produto focado em facilitar a vida do empreendedor autônomo, do MEI ao ME, temos serviços financeiros, contábeis e benefícios para o PJ.

## Como se candidatar

https://smartmei.recruiterbox.com/jobs/fk03z2d?source=Github

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias após cada processo.
E-mail para contato em caso de não haver resposta: recrutamento@smartmei.com.br

## Labels

- PJ
- Pleno
- Remoto
- Go
- Flutter

**Comment by delley** [comment]
@Leticiaschadeck essa vaga ainda está aberta ou podemos fechá-la?

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
