### ISSUE TITLE
[São Paulo] Fullstack Developer na Enova

### ISSUE THREAD

**Issue by alexandreamadocastro** [Gommunity/vagas#7]
**What you’ll be doing:** 

As a Senior Software Engineer, you’ll be designing and implementing technical solutions to business problems. You’ll be a part of the first team in our Brazil office and will also collaborate with engineers in our Chicago office to build the best systems for the problem at hand. Most problems have multiple solutions and we need your expertise to figure out which one is best and drive to completion. In addition, you will work with Product Management, Analytics, and Operations in Chicago to deliver business value.  

Our most successful Senior Engineers are able to tackle a variety of tasks from designing microservices, operational issues, production debugging, risk mitigation and management, and the ability to pair with others outside of your immediate team in order to accomplish any task.  

**What you should have:**

- Experience with any programming language, we welcome engineers from various technical backgrounds
- Fluent in both conversational and business-focused English
- Comfort building features integrating over an API
- Passion for crafting exceptional code, using open source technologies, and continuous learning
- Ability to balance multiple concurrent projects with varying priorities
- Buy vs Build acumen developed in previous roles
- Bachelor’s degree in Computer Science, Engineering, or equivalent experience
- 

**Nice to have:**

- Deployed software using Go, Ruby, Rails,  Linux, Vue.js or PostgreSQL
- Experience with Containers such as Docker or Kubernetes
- AWS skills and/or Certifications
- Working knowledge of modern web standards
- Experience developing web applications 
- Contribute to popular open-source projects (send us GitHub links!)
- Software Engineering Overview:
- The Software Engineering Team, one of the largest groups in the company, is responsible and accountable for meeting the demands of our current and future businesses. We help create the “Tech” in FinTech.

We are structured into small full-stack teams, each aligned to specific business lines or core services. Each team is responsible for defining and delivering solutions through smart interactive development. We code in Ruby and Go, and use Vue.js and other JS frameworks for front-end development. However, we welcome engineers from different technical backgrounds and have a training program to get you up to speed on our tech stack. Baseline is our self-paced training program, which provides a suite of exercises for all new engineering hires to work through during their first few weeks, ensuring they have the knowledge needed to be successful in their role.

Although we are divided into unique teams, our culture of collaboration promotes and encourages engagement across every team and department within the company - no team is a silo. This enables us to align our core values and create strong, best practices. 

**About Enova:** 

Enova is a leading provider of online financial services that leverages its advanced technology and analytics to provide access to credit for non-prime consumers and small businesses. Our roots are in Chicago, but we have served nearly 5 million customers through our six businesses in the U.S. and abroad. We pride ourselves on hiring smart and driven people who bring new and innovative ideas to the table. Our philosophy is, "Life’s short. Work someplace awesome."

Our goal at Enova is to recruit, hire, develop and maintain a diverse workforce. It is our policy to provide equal employment opportunity for all persons and not discriminate in employment decisions by placing the most qualified person in each job, without regard to any other classification protected by federal, state, or local law.

Apply through:
https://boards.greenhouse.io/enova/jobs/1622664

**Comment by delley** [comment]
@alexandreamadocastro a vaga ainda está aberta?

**Comment by delley** [comment]
@alexandreamadocastro a vaga ainda está aberta?

**Comment by delley** [comment]
@alexandreamadocastro a vaga ainda está aberta ou podemos fechá-la?

**Comment by CassioRoos** [comment]
@alexandreamadocastro a vaga ainda esta aberta?

**Comment by delley** [comment]
Vaga aberta a mais de 6 meses. Caso a vaga ainda esteja aberta, reabra a issue.
