### ISSUE TITLE
[São Paulo/SP | REMOTE] – Tech Lead @ Mshield

### ISSUE THREAD

**Issue by rogaha** [Gommunity/vagas#71]
# About Us

**Mshield is an early stage start-up building a next-generation fraud prevention and risk management platform powered by AI and machine learning. Founded by big data and risk management experts, Mshield has one mission: to protect businesses from fraud, while improving customer experience. The company leverages the latest fraud prevention techniques, real-time data and human behavior understanding at scale to have a real impact on the operational and financial performance of companies expanding their presence online. To achieve this, we pay equal attention to developing cutting-edge technology, understanding real-life user patterns and creating innovative ML/AI models.**

Everything you do matters: all your code, machine learning models, advisory, management, and other actions/roles will have a material impact on the way our clients run their business and how effectively we fight fraud and protect people from wrongdoing. You will be able to interact and meet many people from widely different cultures around the world and understand the business like few others. You will be able to say you protect people on a daily basis. You will be challenged with new technology, new processes, and new mindsets and will be asked to contribute to ensure continuous improvement. Join us and let’s change the world together!

## Your Role
You will be a core team member of Mshield’s first ten employees and have a tangible impact on the trajectory of our company reshaping the way we fight against the crime of fraud in the digital era leveraging machine learning and AI. This challenging role will include aspects of hands-on engineering, dev-ops, and project management.

## Responsibilities
Over the first 12-18 months, you will be focusing on generating the following key outcomes:
- Build next-generation applications with a focus on micro-services and back-end services supporting them.
- On basis of the algorithms developed by our data science team, generate production code for our fraud prevention and risk management engines.
- Collaborate with our data science team to develop data pipeline, cloud infrastructure and basic security protocol.
- Oversee and project manage the development of internal productivity tools, and the customer front-end, leveraging internal and external resources.
- Support the company’s product development by building MVPs for rapid prototyping.
- Be an owner of the product, identifying technical debt, proposing concrete solutions.
- Have an active role in the decisions that define the direction of the overall architecture.
- Be a mentor to the rest of the team.

## Requirements 
- 3-5 years’ work experience.
- BS/MS/Phd in Computer Science or related field.
- Proficiency in one or more server-side programming language (e.g. Python, Go, Java, C++, Node).
- Command of Terraform, experience with tools to provision systems infrastructure, including AWS, GoogleCloud etc.
- Experience with large-scale distributed storage (SQL or NoSQL; e.g. MySQL, Cassandra, Redis) and data streaming systems (e.g. Kafka, Hadoop, Hive).
- Knowledge of a backend stack, including technologies like Golang, Java, Node.js.
- Track record shipping high-quality product features on schedule.
 
## Bonus Skills 
- Frameworks like React and React Native are a plus.
- Understanding of the mathematical underpinnings of the learning and optimization models and algorithms, such as algorithms for convex, linear, integer programs and Markov Decision Processes/Reinforcement Learning.
- Experience in fraud prevention and/or risk management.
- Previously developed RESTful APIs.
- Experience with mobile application development using iOS and Android are a plus.

## Contratação

CLT, preferencialmente.

## Como se candidatar

Por favor envie um email para talent@mshield.ai com seu CV anexado - enviar no assunto: Vaga Tech Lead

## Labels

- CLT
- PJ
- Pleno
- Remoto
- Sênior

**Comment by delley** [comment]
@rogaha essa vaga ainda está aberta ou podemos fechá-la?

**Comment by rogaha** [comment]
@delley ainda está aberta.

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
