### ISSUE TITLE
[Remoto | São Paulo/SP] Software Engineer Go na [Pismo]

### ISSUE THREAD

**Issue by erika-donato** [Gommunity/vagas#72]
## Descrição da vaga

Buscamos uma pessoa curiosa e que goste de desafios para compor nosso Time de Engenharia. Construímos aplicações estado-da-arte em microserviços para meios de pagamento, cartão de crédito, carteira digital e outros produtos inovadores utilizados por empresas líderes no varejo e no mercado financeiro.

Se identificou? 
Vamos adorar ter mais um talento como você na nossa empresa!!

## Local

Remoto ou Escritório, São Paulo - Vila Olímpia

## Benefícios

Trabalho 100% remoto
Flexibilidade de horário
Vale Refeição
Vale Alimentação
Vale Transporte
Assistência Médica
Assistência odontológica
Day off de Aniversário
50% Estacionamento
Café da manhã
Espaço de Descompressão
Comidinhas e Sorvete
Happy Hour | Mensal
Home Office

## Requisitos

**Obrigatórios:**
Java, Groovy e Go
Testes automatizados
SQL e NoSQL
Git
APIs Rest e Streaming de dados
Cloud (AWS e Google)
Docker

**Desejáveis:**
Programação reativa
ReactiveX
Vertx
Kubernetes
Continuous Delivery

## Contratação

CLT Full

## Nossa empresa

A missão da Pismo é tornar-se a principal infraestrutura de tecnologia em meios de pagamento no mundo. Para isso, contamos com um time engajado, determinado em fazer o melhor sempre. 

## Como se candidatar

Se aplique em nossa vaga através do site: https://jobs.kenoby.com/pismo/job/software-engineer-backend/5f91eb1ba8de1152c28e7434

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até XX dias após cada processo.
E-mail para contato em caso de não haver resposta: feedbacks@empresasuperlegal.com.br

## Labels

- CLT
- Pleno
- Remoto
- Sênior

**Comment by delley** [comment]
@erika-donato essa vaga ainda está aberta ou podemos fechá-la?

**Comment by erika-donato** [comment]
Ainda temos vagas abertas, pode deixar o anúncio ativo

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
