### ISSUE TITLE
[Porto Alegre] Golang Developer na [Azion Technologies]

### ISSUE THREAD

**Issue by gabrielnes-azion** [Gommunity/vagas#73]
## Descrição da vaga

Sua missão será construir e evoluir softwares de alta disponibilidade e baixa latência que irão prover serviços de edge computing utilizados por milhões de usuários, incluindo as principais plataformas de e-commerce, de ensino à distância, de mídia e do mercado financeiro. Você certamente já utilizou a nossa rede, mesmo sem saber.

Na Azion você deve ser capaz de trabalhar com autonomia, permanentemente atento às tendências, melhores práticas e tecnologias de ponta. Irá participar de discussões técnicas complexas que incluem computação distribuída, processamento de streaming de grandes volumes de dados em tempo real, arquitetura de sistemas de larga escala, orquestração de serviços e infraestrutura, segurança de sistemas, etc.

## Local

Escritório, Porto Alegre, RS, Brazil

## Benefícios

- VT
- VR
- plano de saúde 
- plano odontológico 
- some cool stuff

#### Diferenciais

- Cultura que valoriza a responsabilidade, com um time de alto desempenho;
- Flexibilidade no horário de trabalho;
- Incentivo ($$) para personalizar a sua mesa de trabalho, que já vai contar com um computador Apple;
- Geladeira com bebida liberada (água com gás, refrigerante, cerveja), além de café e chás;
- Folga remunerada no aniversário (um dia aproveitado no período entre 10 dias antes e depois da data);
- Participação em treinamentos e congressos no Brasil e no exterior, com o objetivo de aumentar o conhecimento e networking, gerando inovação e novos negócios.
- Arena com playstation 4, snes, atari, jogos, copa, churrasqueira, etc.

## Requisitos

**Obrigatórios:**
- Desenvolvimento em Golang ou C.
- Conhecimento de protocolos de rede/transporte: IPv4, IPv6, ICMP, TCP, UDP.
- Conhecimento de protocolos na camada de aplicação: HTTP, DNS, BGP, etc.
- Conhecimento de Linux: Comandos shell, gerenciadores de pacotes (rpm, deb), gerenciadores de serviços (systemd).
- Estar cursando ou ser graduado na área de exatas ou experiência equivalente.
- Inglês intermediário.

**Desejáveis:**
- Experiência em virtualização (VM, Docker, Kubernetes).
- Experiência no fluxo e toolchain DevOps/DevSecOps(Plan, Code, Build, Test, Package, Release, Configure, Monitoring, Security). 
- Experiência com times de desenvolvimento e cultura ágil.
- Inglês avançado.

**Diferenciais:**
- Desenvolvimento em Python.
- Experiência com orquestração (puppet, ansible, chef, juju, terraform).

## Contratação

CLT, 44 horas semanais, de segunda a sexta-feira, regime de banco de horas.

## Nossa empresa

Fundada em 2011, a Azion é uma plataforma de Edge Computing que provê a abstração definitiva para alguns dos desafios mais complexos em redes e computação, incluindo escalabilidade, disponibilidade, performance e segurança. A Azion é a resposta para arquiteturas web inovadoras e de missão-crítica necessárias em serviços como e-Commerce, Financeiro, Media e outras aplicações web, além de IOT, realidade aumentada (AR) e realidade virtual (VR).

## Como se candidatar

Apply for this position on http://jobs.azion.com/apply/IY4EuX4m2v/Software-Developer-Golang

## Tempo médio de feedbacks

Costumamos enviar feedbacks as soon as possible.
E-mail para contato em caso de não haver resposta: hcm@azion.com

## Labels

- CLT
- Pleno
- Sênior

**Comment by delley** [comment]
@gabrielnes-azion essa vaga ainda está aberta ou podemos fechá-la?

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
