### ISSUE TITLE
[Remoto] Back-end developer Sênior na Avenue

### ISSUE THREAD

**Issue by alexgarzao** [Gommunity/vagas#89]
## Desafios da vaga

Você está interessado em criar um software que deve realizar transações em milissegundos, com alta disponibilidade, que deve lidar com centenas de milhares de usuários e tudo isso com facilidade de uso e sem perder um centavo?

Se sua resposta for sim, você deve se juntar a nós.

## Descrição da vaga

Nosso back-end é baseado em ferramentas de código aberto e funciona como um conjunto de MicroServiços baseados em Golang. Estamos usando RabbitMQ e gRPC para comunicação. Este backend suporta nosso Web App (um React / Redux & JS SPA) e nosso Mobile App (mecanismo Flutter usando WebViews para renderizar nosso Web App, que logo será totalmente nativo).

- Projetar e implementar novos recursos para nossa plataforma;
- Melhorar o design e funcionalidade existentes;
- Depurar e corrigir problemas;
- Automatizar processos e rotinas existentes.

## Local

Remoto

## Requisitos

- Conhecimento dos fundamentos de CS, incluindo estruturas de dados, design de algoritmos;
- Proficiência em Go;
- Conhecimento básico de mensageria e paralelismo/concorrência.

## Perfil

- Solução de problemas;
- Análise crítica para sugestão de melhorias;
- Autogestão, ownership;
- Compreensão do negócio;
- Alinhamento com propósito da empresa;
- Interesse/experiência com investimentos.

## Contratação

CLT a combinar

## Nossa empresa

https://www.avenue.us/

## Como se candidatar

Maiores informações neste link: https://jobs.kenoby.com/avenue-port/job/desenvolvedor-back-end-senior-remoto/600f2bde88675c113f4a84ca

## Labels

- CLT
- Remoto
- Sênior

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
