### ISSUE TITLE
[Remoto] Backend Developer Go

### ISSUE THREAD

**Issue by ThaysdaCosta** [Gommunity/vagas#9]
## Descrição da vaga

Buscamos **Backend Devs** que possuam **boa experiência prática com GoLang**, e que tenham algum **conhecimento de Angular**.

Atualmente, a stack é composta pela linguagem **GoLang**, banco de dados **MySQL**, front-end feito em **Angular 1.2** (**React** no futuro), **Bootstrap** e a infra está no **Google Cloud**.

Nível: **Pleno**
Modelo: **Remoto**
Carga horária: **Full Time**, em horário comercial.
Início: **Imediato**
Remuneração: **até R$70/h (~R$11.200/mês)**. 💰 A própria pessoa define quanto julga ser adequado receber.

**Sobre nós:** Somos uma comunidade com milhares de profissionais de TI que integra diversas iniciativas, produtos e serviços para a colaboração mútua e desenvolvimento pessoal e profissional de seus integrantes. **Já somos mais de 12.000 pessoas!** 

**Tem interesse e disponibilidade imediata?** Acesse o link https://impulser.me/thays-impulso, entre para a comunidade e me chame diretamente por lá (logo após registrar-se, você receberá por email as credenciais para acessar o nosso chat). Lá na comunidade, eu sou @thays. É só chamar! 

Aguardo vocês!

## Local

Remoto

## Labels

- Pleno
- Remoto
- Sênior

**Comment by delley** [comment]
@ThaysdaCosta a vaga ainda está aberta?

**Comment by ThaysdaCosta** [comment]
Olá, @delley! Essa já foi encerrada. :)

**Comment by delley** [comment]
@ThaysdaCosta vi que você fechou e em seguida reabriu a issue, é uma nova vaga ou posso fechar essa issue?

**Comment by delley** [comment]
@ThaysdaCosta a vaga ainda está aberta?

**Comment by delley** [comment]
@ThaysdaCosta  a vaga ainda está aberta ou podemos fechá-la?

**Comment by ThaysdaCosta** [comment]
Bom dia, Francisco.

A oportunidade foi encerrada. Podemos fechá-la.

Obrigada.


Em ter, 4 de ago de 2020 07:56, Francisco Oliveira <notifications@github.com>
escreveu:
