### ISSUE TITLE
[Remoto/Florianópolis - SC] Analista de Integrações na fluidapi

### ISSUE THREAD

**Issue by lffranca** [Gommunity/vagas#90]
## Nossa empresa

A [Fluid](https://www.fluidapi.io/) é uma solução de transformação digital para os nossos clientes! Startup integrante do grupo Nkey, ambas baseadas em Florianópolis, com atuação nacional e internacional. Em 2020 fomos acelerados pelo Inovativa Brasil, StartupSC e incubados no MIDITEC da ACATE.

Nossas soluções de API Management, iPaaS e serviços profissionais simplificam a integração e gerenciamento de APIs de nossos clientes. Trabalhamos com diversas tecnologias e sistemas para fornecer soluções aos nossos clientes em todos os setores.

### Nosso propósito é eliminar barreiras de integração

Conectando empresas e sistemas de forma ágil, segura e escalável. Eliminamos barreiras, integramos sistemas e orquestramos dados entre sistemas e empresas, simplificando desenvolvimento e gerenciamento de APIs e Integrações.

## Descrição da vaga

Como analista de integração em nossa equipe, você terá a oportunidade de ajudar nossos clientes com seu processo de transformação digital utilizando a Fluid. Você terá um papel fundamental: se estabelecer como especialista no assunto de uma empresa líder em inovação no setor de serviços de integração.

### Principais atividades:

- Definição e construção de de workflows de integração;
- Participação em atividades com os clientes de provas de conceito, apresentações técnicas, etc
- Ações da Fluid para os clientes, aprimorando o processo de levantamento de requisitos e implementações;
- Executar implementação Evangelizar estruturas, entregas do projeto, melhores práticas / políticas e implementações;
- Identificar oportunidades para expandir a área de cobertura da Fluid e impulsionar outros serviços;
- Identificar riscos contínuos e pontos problemáticos ao longo das experiências do projeto em campo e contribuir para o desenvolvimento e implementação de medidas internas de mitigação para atender às necessidades do cliente;
- Identificar oportunidades de eficiências no modelo operacional de TI dos para obter maior valor da plataforma Fluid;
- Realizar apresentações, elaborar documentos de projeto arquitetônico e workshops de coleta de requisitos para influenciar a direção estratégica de nossos projetos e levar os clientes através do design da solução;

### Requisitos:

- Desejável conhecimento em Golang, GraphQL, JSON Logic, RabbitMQ, Kafka, e Jaegger
- Experiências demonstradas desenvolvendo integrações de serviços com as principais ferramentas do mercado;
- Conhecimento de plataformas de ERP, CRM, e-commerce, etc.
- Conhecimento prático de infra-estruturas locais / baseadas em nuvem, JSON, pipelines SDLC e implantações / configurações e definição / evangelização de melhores práticas / padrões;
- Capacidade demonstrada de arquitetar efetivamente soluções dentro de uma equipe técnica diversificada de clientes;
- Experiência demonstrada com parâmetros de alta disponibilidade, tolerância a falhas, testes de desempenho e ajuste em vários compromissos
- Experiência com implementação e suporte de soluções técnicas de nível corporativo que atendem a requisitos de negócios complexos, ao evangelizar metodologias de integração

## O que você encontra por aqui

- Time descontraído e colaborativo;
- Trabalho remoto ou híbrido;
- Possibilidade de morar na Ilha da Magia! (Florianópolis - SC);
- Metodologias ágeis;
- Paixão por tecnologia;
- Day off no mês de aniversário;
- No Dress Code; queremos que você se sinta livre para ser quem é;
- Oportunidade de compartilhar conhecimento;
- Happy hours com o time;
- Encontros semanais de conversação em inglês;
- Reembolso para cursos de treinamento.

## Local

Remoto ou Híbrido, Florianópolis - SC

## Contratação

- PJ

## Como se candidatar

Por favor envie um email para eluane.vasata@nkey.com.br com seu CV anexado ou linkedin - enviar no assunto: "[FLUID] Analista de Intetegrações"

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👶 Pleno
- 👶 Sênior
- ⚖️ A-Combinar
- ⚖️ PJ

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
