### ISSUE TITLE
[VAGA 100% REMOTA] Flutter Developer

### ISSUE THREAD

**Issue by Startec-Jobs** [Gommunity/vagas#91]
## Nossa empresa

A Ideagri oferece soluções em tecnologia para a gestão agropecuária. Há 13 anos no mercado, a empresa surgiu com a constatação de uma demanda por softwares de gestão rural. 

Localizada em Belo Horizonte (MG), a Ideagri oferece um software em modelo SaaS para que o seu cliente possa ter controle dos dados técnicos e financeiros para melhorar seu negócio, tudo isso dentro de um sistema de administração. 

A empresa possui hoje a capacidade de atender atividades de agricultura, incluindo a cafeicultura, e pecuária de corte e pecuária leiteira, onde o software gerencia desde as rotinas zootécnicas como a apuração dos custos de produção. 

A Ideagri entrega a melhor plataforma para a gestão estratégica do agronegócio. 

## Descrição da vaga

A Ideagri está com vaga aberta para pessoa desenvolvedora em Flutter! Buscamos uma pessoa experiente, com habilidade para trabalhar em equipe e com determinação para fortalecer o maior software de gestão do agrobusiness. 

## Requisitos

**Obrigatórios:**
- Experiência de 4 anos ou mais com desenvolvimento
- Conhecimento em Flutter
- Conhecimento em Dart

**Desejáveis:**
- Conhecimento em APIs RESTful
- Conhecimento em Git
- Desenvolvimento orientado a testes
- Experiência com desenvolvimento nativo (Android ou iOS)
- Conhecimento em ferramentas para automação de build e integração contínua
- Experiência com metodologias ágeis

## Contratação

R$ 8.000,00 a R$ 10.000,00 (PJ)

## Local

Remoto

## Benefícios

- Computador corporativo

## Como se candidatar

Através do link: http://bit.ly/devflut 

## Labels

- Alocado
- PJ
- Sênior
- Remoto
- 8k a 10k

**Comment by joivo** [comment]
Onde há Golang nesta vaga?

**Comment by delley** [comment]
@Startec-Jobs esse repositório é específico para vagas Go. Logo, estou fechando essa issue.
