### ISSUE TITLE
[Remoto] Backend developer @ Levee

### ISSUE THREAD

**Issue by renatoaquino** [Gommunity/vagas#92]
### Sobre a Levee

Levee é uma empresa nascida no Vale do Silício, Califórnia/EUA, e temos como objetivo usar tecnologia para impactar a sociedade contribuindo com a sustentabilidade e a ampliação da produtividade das empresas através de nossos produtos. Possuimos a plataforma [Emprego Ligado](https://www.empregoligado.com.br), que é a maior gestora de vagas operacionais na América Latina. Utilizamos touchpoints digitais (mobile app, progressive web app, chat-bot) e inteligência artificial para trazer empregabilidade aqueles que mais precisam, as classes C, D e E, que representam 85% da força de trabalho no país. Você será responsável pela primeira impressão dos futuros clientes da Levee! Venha nos ajudar a revolucionar o mundo, buscamos profissionais apaixonados por tecnologia!

Um pouco mais sobre a Levee:

[LEVEE na EXAME](https://exame.abril.com.br/negocios/faltas-atrasos-e-transito-um-ralo-que-custa-milhoes-as-grandes-empresas/)

[LEVEE @ MIT](https://www.mitinclusiveinnovation.com/winners/levee/)

### Requirements

Aqui você será responsável por desenvolver soluções escaláveis, colocar a mão na massa em APIs REST, GraphQL, Lambdas e também gRPC por isso esperamos que você tenha:

- Experiência profissional com GO ou Ruby;
- Experiência no desenvolvimento de microsserviços/APIs;
- Conhecimento em programação assíncrona;
- Facilidade em trabalhar dentro de times multidisciplinares utilizando metodologias ágeis;
- Ter boa capacidade de abstração;
- Preocupação, desde o começo, com clean code (código simples, estruturado, com testes unitários e melhoria contínua);
- TDD e testes de integração;
- Sistemas de versionamento de código. Preferencialmente git;
- Oh, we almost forgot. You’ll be doing a lot of reading, writing, and talking in English!

### Diferenciais:

- Experiência com logging e documentação de código;
- Experiência em sistemas georreferenciados;
- Ops (AWS);
- Experiência/interesse em Machine Learning;
- Docker

### Benefits

- Contratação em regime CLT com salário compatível com o mercado;
- Plano de carreira;
- VR ou VA no valor de R$ 33;
- Plano de saúde e odontológico coparticipação Sulamérica extendido para dependentes e cônjuge;
- Parceria com o SESC;
- Full remote.

https://apply.workable.com/levee/j/5B6F7667BC/

**Comment by masisiliani** [comment]
@renatoaquino vaga em qual nível?

**Comment by renatoaquino** [comment]
> @renatoaquino vaga em qual nível?

Pleno ou Sênior.
