### ISSUE TITLE
[REMOTO] Backend Developer Sênior na NEON

### ISSUE THREAD

**Issue by Luana-vargas** [Gommunity/vagas#96]
A Neon está buscando uma pessoa Desenvolvedora Backend Sênior que seja movida por novos desafios para que continuemos fazendo o incrível - simplificar a vida dos nossos clientes! :)
Se você se sente à vontade em trabalhar em equipe, dando e recebendo feedbacks, é inquieto com a mesmice e seu combustível diário é programar, a Neon é onde você vai querer estar!! :)

## Responsabilidades e atribuições 
- Atuação ativa em squads multidisciplinares e rituais ágeis (desde a concepção até o delivery do produto/projeto/feature/melhoria);
- Planejamento do trabalho de codificação;
- Implementação de features/melhorias;
- Realizar os testes;
- Code review;
- Clean Code;
- Qualidade de código.

## Requisitos 
- Conhecimentos em Golang.
- Integração com áreas cross; Engenharia + Arquitetura + Segurança da Informação + Qualidade + SRE
- Expertise em desenvolvimento de software e integrações de Restful APIs;
- Engenharia de software: DDD / SOLID / paradigma funcional / gitflow.
- Bancos de dados: SQL Server e MongoDB.
- Cloud: AWS.
- Containers: Docker + Kubernetes.
- Broker de mensagens: Kafka / RabbitMQ.
- Monitoria: Dynatrace + Grafana
- Log: ELK.

## Diferenciais 
- Conhecimentos em uma das linguagens de programação: .Net Core e Node.js.
- API Gateway: Sensedia.
- Qualidade de código: SonarQube.
- Cofre de senhas: Vault.
- Segurança de código: Veracode.

## Local
- Remoto \o/

## Benefícios
- Benefícios flexíveis, a sua escolha!

## Contratação
- CLT Full

## Como se candidatar

Para se candidatar, basta aplicar para a vaga aqui: https://www.linkedin.com/jobs/view/2436449368

Na Neon, acreditamos que ao trabalhar com um time diverso e inclusivo, somos capazes de criar produtos que atendam a todos. É por isso que as vagas da Neon também estão abertas para pessoas com deficiência (PcD)

## Labels
- CLT
- Remoto
- Sênior

**Comment by Ocelani** [comment]
close

**Comment by Ocelani** [comment]
@Luana-vargas 
close

**Comment by delley** [comment]
Caso a vaga ainda esteja aberta, por favor, abrir uma nova issue!
